import { contentLocale } from '@/lib/locale'
import type {Locale} from '@/lib/types'
import {LocaleLink} from '@/components/locale-link'
const copy={
 'pt-BR':{title:'Quatro formatos instantâneos para comparar',intro:'Jogos instantâneos não seguem uma única regra. Compare a escolha feita antes da rodada, a revelação do resultado e a possibilidade de encerrar a participação.',items:[['plinko','Plinko','A bolinha atravessa pinos até um multiplicador. Risco e fileiras são escolhas anteriores à queda.'],['mines','Mines','A interação acontece ao revelar casas. É possível encerrar a sequência antes de outra escolha, conforme as regras do jogo.'],['spribe-dice','Dice','Um resultado numérico é comparado com um limite. Não há curva de multiplicador para acompanhar em tempo real.'],['spribe-keno','Keno','Números escolhidos são comparados com um sorteio. Esta ficha trata da edição de 36 números da SPRIBE.']]},
 en:{title:'Four instant formats to compare',intro:'Instant games do not share a single rule set. Compare the decision before a round, how results are revealed and whether participation can end between choices.',items:[['plinko','Plinko','A ball passes through pegs toward a multiplier. Risk and rows are chosen before the drop.'],['mines','Mines','Interaction centers on revealing tiles. The sequence can end before another choice, subject to the game rules.'],['spribe-dice','Dice','A numerical result is compared with a threshold. There is no rising multiplier curve to follow in real time.'],['spribe-keno','Keno','Chosen numbers are compared with a draw. This reference covers SPRIBE’s 36-number edition.']]},
 'es-MX':{title:'Cuatro formatos instantáneos para comparar',intro:'Los juegos instantáneos no comparten una sola regla. Compara la decisión antes de la ronda, la revelación del resultado y la posibilidad de terminar entre elecciones.',items:[['plinko','Plinko','Una pelota atraviesa clavijas hasta un multiplicador. El riesgo y las filas se eligen antes de soltarla.'],['mines','Mines','La interacción consiste en revelar casillas. Se puede terminar la secuencia antes de otra elección, según las reglas del juego.'],['spribe-dice','Dice','Un resultado numérico se compara con un umbral. No hay una curva creciente de multiplicador que seguir en tiempo real.'],['spribe-keno','Keno','Los números elegidos se comparan con un sorteo. Esta ficha corresponde a la edición de 36 números de SPRIBE.']]},
}
export function InstantGuide({locale}:{locale:Locale}){const c=copy[contentLocale(locale)];return <section className="mb-8"><h2 className="text-2xl font-bold">{c.title}</h2><p className="my-4 max-w-3xl text-muted-foreground">{c.intro}</p><div className="grid gap-4 sm:grid-cols-2">{c.items.map(([slug,title,body])=><article key={slug} className="rounded-xl border border-border p-5"><h3 className="font-semibold"><LocaleLink className="text-primary" href={`/games/${slug}`}>{title} →</LocaleLink></h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p></article>)}</div></section>}
