import type { Locale } from '@/lib/types'
import { FOOTBALL_CARDS } from '../football-cards'
import type { GolacoSymbol } from './config'

const ptBR = {
  seoTitle: 'Liva Golaço: slot de futebol grátis com rodadas grátis',
  description: 'Slot de futebol grátis do PlayLiva: caça-níquel com 243 formas, troféus que dão rodadas grátis e a Sequência de Gols até ×5. Só créditos virtuais.',
  ...FOOTBALL_CARDS.golaco['pt-BR'],
  spin: 'Girar', spinning: 'Girando…', bet: 'Valor da rodada', win: 'Ganho', ready: 'Bola rolando!', noWin: 'Sem ganho nesta rodada',
  freeSpins: 'Rodadas grátis', streak: 'Sequência de gols', finalBonus: 'Final de Ouro', begin: 'Entrar em campo', again: 'Jogar de novo',
  bonusTotal: 'Total do bônus', bonusComplete: 'Fim de jogo!', spinsPlayed: 'Rodadas grátis jogadas', plusSpin: 'Rodada grátis',
  introNote: 'Cada bola de ouro: GOL e +1 na sequência, até ×5 · Cada troféu: +1 rodada',
  bigWin: 'Grande ganho', superWin: 'Super ganho', megaWin: 'Golaço!', ways: '243 formas', wild: 'CURINGA', scatter: 'BÔNUS', goal: 'GOL!',
  loading: 'Enchendo o estádio…', loadError: 'Não foi possível carregar as imagens. Seus créditos estão seguros.', retry: 'Tentar novamente',
  insufficient: 'Liva Credits insuficientes. Reduza o valor ou restaure o saldo demo.',
  unavailable: 'Rodada indisponível. Nenhum crédito foi usado. Tente novamente quando estiver pronto.',
  settlementError: 'Não foi possível registrar o pagamento. Nenhum ganho foi creditado. Restaure o saldo demo para continuar.',
  how: 'Como jogar', rules: 'Combine um símbolo comum em 3, 4 ou 5 rolos seguidos, a partir da esquerda, em qualquer linha. Só a combinação mais longa de cada símbolo paga, e a quantidade de símbolos iguais em cada rolo multiplica as formas. Cinco rolos × três linhas = 243 formas. O retorno pode ser menor que o valor da rodada.',
  wildRules: 'A Camisa 10 é o curinga: aparece nos rolos 2 a 5 e substitui os símbolos comuns, nunca o Troféu nem a Bola de Ouro. Curingas e troféus não pagam sozinhos.',
  bonusRules: '3, 4 ou 5+ Troféus em qualquer posição de uma rodada paga (não precisam estar vizinhos) dão 8, 12 ou 20 rodadas grátis no Final de Ouro, com o mesmo valor. Nas rodadas grátis aparece a Bola de Ouro: cada uma que cai marca um GOL e soma +1 à Sequência de Gols (começa em ×1, máximo ×5), antes do pagamento da própria rodada, e a sequência vale até o fim do bônus e multiplica os ganhos. Cada Troféu nas rodadas grátis dá +1 rodada grátis, até 40 rodadas por bônus. Pagamento máximo por rodada: 1.000× o valor.',
  interruption: 'Demo local. Sair ou recarregar encerra rodadas pendentes e rodadas grátis não usadas, sem devolução. Créditos já registrados permanecem. Evite usar a mesma carteira em várias abas.',
  paytable: 'Tabela de pagamentos', paytableNote: 'Múltiplos do valor total da rodada por forma, para 3 / 4 / 5 rolos, antes da Sequência de Gols. Todas as formas são somadas e o pagamento é arredondado para baixo uma única vez, até 0,01 Liva Credit.',
  reel: 'Rolo', row: 'linha', result: 'Resultado dos rolos',
  symbols: { camisa: 'Camisa 10 curinga', taca: 'Troféu bônus', gol: 'Bola de Ouro (gol)', chuteira: 'Chuteira de ouro', luvas: 'Luvas de goleiro', apito: 'Apito', medalha: 'Medalha', bandeira: 'Bandeira de escanteio', cartoes: 'Cartões', refletor: 'Refletor do estádio', cone: 'Cone de treino' } as Record<GolacoSymbol, string>,
  notice: 'Jogo grátis · Sem depósitos ou saques · Sem valor monetário. Não é um jogo certificado nem de dinheiro real.',
  articleTitle: 'Slot de futebol grátis com rodadas grátis e bônus',
  articleIntro: 'Liva Golaço é um PlayLiva Original: um caça-níquel de futebol com clima de final de campeonato — estádio lotado, refletores acesos e confete no ar. Gire os rolos, combine chuteiras, luvas, apitos e medalhas em 243 formas e deixe a Camisa 10 completar as jogadas.',
  articleBonus: 'Três Troféus abrem o Final de Ouro, com 8, 12 ou 20 rodadas grátis. Lá dentro, cada Bola de Ouro é gol: a Sequência de Gols sobe até ×5 e multiplica os ganhos até o apito final. É um jogo de futebol grátis para se divertir — no PlayLiva não há apostas em dinheiro, só Liva Credits virtuais.',
  rulesTitle: 'Regras do Liva Golaço',
  ruleList: [
    'Cada rodada usa Liva Credits virtuais, sem valor monetário. O valor vai de 1,00 a 50,00 créditos.',
    '5 rolos × 3 linhas, 243 formas: combinações de 3, 4 ou 5 símbolos iguais em rolos seguidos a partir da esquerda.',
    'Camisa 10 é o curinga (rolos 2 a 5) e substitui os símbolos comuns.',
    '3 / 4 / 5+ Troféus em qualquer lugar dão 8 / 12 / 20 rodadas grátis.',
    'Nas rodadas grátis, cada Bola de Ouro soma +1 à Sequência de Gols (×1 até ×5), que multiplica os ganhos até o fim do bônus.',
    'Cada Troféu nas rodadas grátis dá +1 rodada grátis, com limite de 40 rodadas por bônus.',
    'O resultado de cada rodada é definido antes de os rolos pararem; animação e som só mostram esse resultado.',
  ],
  creditsTitle: 'Créditos virtuais, emoção de final',
  credits: 'Você joga com um saldo demo de Liva Credits que pode ser restaurado quando quiser. Nada disso vale dinheiro, e não há depósitos nem saques. Para conhecer slots de provedores e onde jogá-los no seu mercado, explore o catálogo separado do PlayLiva.',
  breadcrumbOriginals: 'PlayLiva Originals',
}
type GolacoCopy = typeof ptBR

const en: GolacoCopy = {
  seoTitle: 'Liva Golaço: free football slot with free spins',
  description: 'A free football slot from PlayLiva: 243 ways, trophies that award free spins and a Goal Streak up to ×5. Virtual credits only, no deposits.',
  ...FOOTBALL_CARDS.golaco['en'],
  spin: 'Spin', spinning: 'Spinning…', bet: 'Credits per spin', win: 'Win', ready: 'Kick-off!', noWin: 'No win this spin',
  freeSpins: 'Free Spins', streak: 'Goal Streak', finalBonus: 'Final de Ouro', begin: 'Take the field', again: 'Play again',
  bonusTotal: 'Bonus total', bonusComplete: 'Full time!', spinsPlayed: 'Free spins played', plusSpin: 'Free Spin',
  introNote: 'Every golden ball: GOAL and +1 streak, up to ×5 · Every trophy: +1 spin',
  bigWin: 'Big win', superWin: 'Super win', megaWin: 'Golaço!', ways: '243 ways', wild: 'WILD', scatter: 'BONUS', goal: 'GOAL!',
  loading: 'Filling the stadium…', loadError: 'Artwork could not load. Your credits are safe.', retry: 'Retry',
  insufficient: 'Not enough Liva Credits. Lower your bet or reset the demo balance.',
  unavailable: 'Spin unavailable. No stake was taken. Try again when ready.',
  settlementError: 'The payout could not be booked. No win has been recorded. Reset the demo balance to continue.',
  how: 'How to play', rules: 'Match a regular symbol on 3, 4 or 5 adjacent reels from the left, on any row. Only each symbol’s longest combination pays, and matching symbols on each reel multiply the ways. Five reels × three rows = 243 ways. Returns may be less than your bet.',
  wildRules: 'The No. 10 Shirt is Wild: it appears on reels 2–5 and replaces regular symbols, never the Trophy or the Golden Ball. Wilds and Trophies have no payout of their own.',
  bonusRules: '3, 4 or 5+ Trophies anywhere on a paid spin (no adjacency needed) award 8, 12 or 20 Final de Ouro free spins at that bet. Free spins add the Golden Ball: every one that lands scores a GOAL and adds +1 to the Goal Streak (starts at ×1, maximum ×5) before that spin pays; the streak lasts for the rest of the bonus and multiplies wins. Every Trophy during free spins adds +1 free spin, up to 40 free spins per bonus. Maximum payout per spin: 1,000× bet.',
  interruption: 'Local demo only. Leaving or reloading ends pending spins and unused free spins without a refund. Already booked credits remain. Avoid playing the same wallet in multiple tabs.',
  paytable: 'Paytable', paytableNote: 'Total-bet multiples per way for 3 / 4 / 5 reels, before the Goal Streak. All ways are summed, then the payout is rounded down once to 0.01 Liva Credits.',
  reel: 'Reel', row: 'row', result: 'Reel result',
  symbols: { camisa: 'No. 10 Shirt Wild', taca: 'Trophy Bonus', gol: 'Golden Ball (goal)', chuteira: 'Golden boot', luvas: 'Goalkeeper gloves', apito: 'Whistle', medalha: 'Medal', bandeira: 'Corner flag', cartoes: 'Referee cards', refletor: 'Stadium floodlight', cone: 'Training cone' },
  notice: 'Free play · No deposits or withdrawals · No monetary value. Not a certified or real-money game.',
  articleTitle: 'A free football slot with free spins and a bonus',
  articleIntro: 'Liva Golaço is a PlayLiva Original: a football slot with cup-final energy — a packed stadium, floodlights blazing and confetti in the air. Spin the reels, line up boots, gloves, whistles and medals across 243 ways and let the No. 10 Shirt finish the move.',
  articleBonus: 'Three Trophies open the Final de Ouro with 8, 12 or 20 free spins. Inside, every Golden Ball is a goal: the Goal Streak climbs up to ×5 and multiplies wins until the final whistle. It is a free football game for fun — there is no real-money betting on PlayLiva, only virtual Liva Credits.',
  rulesTitle: 'Liva Golaço rules',
  ruleList: [
    'Every spin uses virtual Liva Credits with no monetary value. Bets range from 1.00 to 50.00 credits.',
    '5 reels × 3 rows, 243 ways: 3, 4 or 5 matching symbols on adjacent reels from the left.',
    'The No. 10 Shirt is Wild (reels 2–5) and replaces regular symbols.',
    '3 / 4 / 5+ Trophies anywhere award 8 / 12 / 20 free spins.',
    'During free spins every Golden Ball adds +1 to the Goal Streak (×1 up to ×5), which multiplies wins for the rest of the bonus.',
    'Every Trophy during free spins adds +1 free spin, capped at 40 free spins per bonus.',
    'Each result is fixed before the reels stop; animation and sound only show it.',
  ],
  creditsTitle: 'Virtual credits, cup-final excitement',
  credits: 'You play with a demo balance of Liva Credits that you can reset at any time. None of it is worth money, and there are no deposits or withdrawals. To discover provider slots and where to play them in your market, explore PlayLiva’s separate catalog.',
  breadcrumbOriginals: 'PlayLiva Originals',
}

const esMX: GolacoCopy = {
  seoTitle: 'Liva Golaço: slot de futbol gratis con giros gratis',
  description: 'Slot de futbol gratis de PlayLiva: 243 formas, trofeos que dan giros gratis y una Racha de Goles hasta ×5. Solo créditos virtuales, sin depósitos.',
  ...FOOTBALL_CARDS.golaco['es-MX'],
  spin: 'Girar', spinning: 'Girando…', bet: 'Cantidad por giro', win: 'Ganancia', ready: '¡Arranca el partido!', noWin: 'Sin ganancia en este giro',
  freeSpins: 'Giros gratis', streak: 'Racha de goles', finalBonus: 'Final de Ouro', begin: 'Salir a la cancha', again: 'Jugar de nuevo',
  bonusTotal: 'Total del bono', bonusComplete: '¡Final del partido!', spinsPlayed: 'Giros gratis jugados', plusSpin: 'Giro gratis',
  introNote: 'Cada balón de oro: GOL y +1 a la racha, hasta ×5 · Cada trofeo: +1 giro',
  bigWin: 'Gran ganancia', superWin: 'Súper ganancia', megaWin: '¡Golazo!', ways: '243 formas', wild: 'COMODÍN', scatter: 'BONO', goal: '¡GOL!',
  loading: 'Llenando el estadio…', loadError: 'No se pudieron cargar las imágenes. Tus créditos están seguros.', retry: 'Reintentar',
  insufficient: 'Liva Credits insuficientes. Reduce la cantidad o restablece el saldo demo.',
  unavailable: 'Giro no disponible. No se descontó ningún crédito. Inténtalo cuando esté listo.',
  settlementError: 'No se pudo registrar el pago. No se acreditó ninguna ganancia. Restablece el saldo demo para continuar.',
  how: 'Cómo jugar', rules: 'Combina un símbolo normal en 3, 4 o 5 rodillos consecutivos desde la izquierda, en cualquier fila. Solo paga la combinación más larga de cada símbolo, y los símbolos iguales en cada rodillo multiplican las formas. Cinco rodillos × tres filas = 243 formas. El retorno puede ser menor que la cantidad jugada.',
  wildRules: 'La Playera 10 es comodín: aparece en los rodillos 2 a 5 y sustituye símbolos normales, nunca el Trofeo ni el Balón de Oro. Los comodines y trofeos no pagan por sí solos.',
  bonusRules: '3, 4 o 5+ Trofeos en cualquier posición de un giro pagado (no tienen que estar juntos) dan 8, 12 o 20 giros gratis de la Final de Ouro con la misma cantidad. En los giros gratis aparece el Balón de Oro: cada uno que cae marca GOL y suma +1 a la Racha de Goles (empieza en ×1, máximo ×5) antes de pagar ese giro; la racha dura el resto del bono y multiplica las ganancias. Cada Trofeo en los giros gratis da +1 giro gratis, hasta 40 giros por bono. Pago máximo por giro: 1,000× la cantidad.',
  interruption: 'Demo local. Salir o recargar termina los giros pendientes y los giros gratis sin usar, sin devolución. Los créditos ya registrados permanecen. Evita usar la misma cartera en varias pestañas.',
  paytable: 'Tabla de pagos', paytableNote: 'Múltiplos de la cantidad total por forma para 3 / 4 / 5 rodillos, antes de la Racha de Goles. Se suman todas las formas y se redondea hacia abajo una sola vez a 0.01 Liva Credits.',
  reel: 'Rodillo', row: 'fila', result: 'Resultado de los rodillos',
  symbols: { camisa: 'Playera 10 comodín', taca: 'Trofeo bono', gol: 'Balón de Oro (gol)', chuteira: 'Tachones de oro', luvas: 'Guantes de portero', apito: 'Silbato', medalha: 'Medalla', bandeira: 'Banderín de córner', cartoes: 'Tarjetas', refletor: 'Reflector del estadio', cone: 'Cono de entrenamiento' },
  notice: 'Juego gratis · Sin depósitos ni retiros · Sin valor monetario. No es un juego certificado ni de dinero real.',
  articleTitle: 'Un slot de futbol gratis con giros gratis y bono',
  articleIntro: 'Liva Golaço es un PlayLiva Original: un slot de futbol con ambiente de final — estadio lleno, reflectores encendidos y confeti en el aire. Gira los rodillos, combina tachones, guantes, silbatos y medallas en 243 formas y deja que la Playera 10 complete la jugada.',
  articleBonus: 'Tres Trofeos abren la Final de Ouro con 8, 12 o 20 giros gratis. Adentro, cada Balón de Oro es gol: la Racha de Goles sube hasta ×5 y multiplica las ganancias hasta el silbatazo final. Es un juego de futbol gratis para divertirse: en PlayLiva no se apuesta dinero real, solo Liva Credits virtuales.',
  rulesTitle: 'Reglas de Liva Golaço',
  ruleList: [
    'Cada giro usa Liva Credits virtuales, sin valor monetario. La cantidad va de 1.00 a 50.00 créditos.',
    '5 rodillos × 3 filas, 243 formas: 3, 4 o 5 símbolos iguales en rodillos consecutivos desde la izquierda.',
    'La Playera 10 es comodín (rodillos 2 a 5) y sustituye símbolos normales.',
    '3 / 4 / 5+ Trofeos en cualquier lugar dan 8 / 12 / 20 giros gratis.',
    'En los giros gratis cada Balón de Oro suma +1 a la Racha de Goles (×1 a ×5), que multiplica las ganancias el resto del bono.',
    'Cada Trofeo en los giros gratis da +1 giro gratis, con límite de 40 giros por bono.',
    'Cada resultado se fija antes de que paren los rodillos; la animación y el sonido solo lo muestran.',
  ],
  creditsTitle: 'Créditos virtuales, emoción de final',
  credits: 'Juegas con un saldo demo de Liva Credits que puedes restablecer cuando quieras. Nada de esto vale dinero y no hay depósitos ni retiros. Para conocer slots de proveedores y dónde jugarlos en tu mercado, explora el catálogo independiente de PlayLiva.',
  breadcrumbOriginals: 'PlayLiva Originals',
}

const COPY: Record<Locale, GolacoCopy> = { 'pt-BR': ptBR, en, 'es-MX': esMX }
export const golacoCopy = (locale: Locale): GolacoCopy => COPY[locale]
