import type {GrowthData} from '@/lib/owner/server/overview'
import {Panel,Table,Metric} from './ui'
import styles from './owner.module.css'
export function DiscoveryHealth({data}:{data:GrowthData}){
 const health=data.discovery
 return <><Panel title="Discovery inventory and crawl health" sub="Catalog/configuration facts. These are not Google traffic or indexing measurements."><div className={styles.miniMetrics}><Metric title="Provider games" value={String(health.realGames)} note={`${health.artwork} with approved artwork`}/><Metric title="PlayLiva Originals" value={String(health.originals)} note="Distinct free-play experiences"/><Metric title="Sitemap URLs" value={String(health.sitemapCount)} note="Current configuration; page filters apply"/><Metric title="Observed orphan pages" value={String(health.crawl.orphans)} note={`${health.crawl.count} URLs crawled`}/></div><p className={styles.inlineNote}>Link evidence: {health.crawl.environment}, {health.crawl.observedAt.slice(0,10)}. {health.crawl.duplicates} duplicate metadata groups; {health.crawl.failures} crawl defects. Configuration changes do not automatically refresh this snapshot.</p><p className={styles.inlineNote}>Verified RTP records: {health.verifiedRtp}; unavailable: {health.unknownRtp}. Missing RTP, volatility or operator availability is never filled with estimates.</p></Panel>
 <Panel title="Topic cluster coverage" sub="Inventory counts and curated internal paths, not a ranking score."><Table headings={['Category','Real games','Originals','Providers','Editorial paths']}>{health.clusters.map(c=><tr key={c.category}><td>{c.category}</td><td>{c.games}</td><td>{c.originals}</td><td>{c.providers}</td><td>{c.editorialPaths}</td></tr>)}</Table><details><summary>Provider inventory</summary><Table headings={['Provider','Documented games']}>{health.providers.map(p=><tr key={p.route}><td>{p.name}</td><td>{p.games}</td></tr>)}</Table></details></Panel>
 <Panel title="Quality and indexability queue" sub="The same decisions drive metadata and sitemap inclusion."><p>{health.quality.filter(g=>g.index).length} qualifying entity/locale pages. {health.quality.filter(g=>!g.index).length} held for content/artwork. {health.excludedAvailability.length} empty or ineligible availability/locale pages excluded.</p><details><summary>View held pages and reasons</summary><Table headings={['Route','Reason']}>{health.quality.filter(g=>!g.index).map(g=><tr key={g.route}><td>{g.route}</td><td>{g.reasons.join('; ')}</td></tr>)}{health.excludedAvailability.map(g=><tr key={g.route}><td>{g.route}</td><td>{g.decision.reasons.join('; ')}</td></tr>)}</Table></details><details><summary>Weak incoming links ({health.weak.length})</summary><Table headings={['Route','Incoming pages','Outgoing pages']}>{health.weak.map(g=><tr key={g.path}><td>{g.path}</td><td>{g.inbound}</td><td>{g.outbound}</td></tr>)}</Table></details></Panel></>
}
