import Link from 'next/link'
import Image from 'next/image'
import { ArrowUpRight, CircleHelp, Clapperboard, FileText, Radio, Search, ShieldCheck } from 'lucide-react'
import type { ReactNode } from 'react'
import { growthData, type GrowthData } from '@/lib/owner/server/overview'
import { filterCreatives } from '@/lib/owner/social-model'
import { withMedia } from '@/lib/owner/server/social'
import { CONTENT_STATES, type Creative, type Source } from '@/lib/owner/model'
import { ActionForm, VideoPreview } from './actions'
import styles from './owner.module.css'
import { GenerationPanel, GeneratedActions } from './generation'

type Section = 'overview' | 'social' | 'seo' | 'affiliate' | 'content'
const headings: Record<Section, [string, string]> = {
  overview: ['Growth overview', 'Know what is ready, what is measured, and what needs attention.'],
  social: ['Creative library', 'Review the work. Keep every publishing decision deliberate.'],
  seo: ['Search performance', 'Find opportunities in evidence. Keep indexing claims precise.'],
  affiliate: ['Affiliate performance', 'Understand exposure and clicks across the PlayLiva journey.'],
  content: ['Content pipeline', 'Turn measured opportunities and coverage gaps into the next useful piece.'],
}
const label = (value: string) => value.replaceAll('_', ' ').replace(/^./, c => c.toUpperCase())
const n = (value?: number | null) => value == null ? '—' : new Intl.NumberFormat('en').format(value)
const percent = (value?: number | null) => value == null ? '—' : `${(value * 100).toFixed(1)}%`
const date = (value?: string | null) => value ? value.slice(0, 10) : 'Not recorded'
function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: string }) { return <span className={styles.badge} data-tone={tone}>{children}</span> }
function Status({ value }: { value: string }) { return <Badge tone={['connected', 'approved', 'published', 'Indexed', 'passed'].includes(value) ? 'green' : ['rejected', 'failed', 'unavailable', 'historical_deleted'].includes(value) ? 'amber' : ['needs_review', 'Requested', 'queued'].includes(value) ? 'blue' : 'neutral'}>{label(value)}</Badge> }
function Panel({ title, sub, children, action }: { title: string; sub?: string; children: ReactNode; action?: ReactNode }) { return <section className={styles.panel}><header className={styles.panelHeader}><div><h2>{title}</h2>{sub && <p>{sub}</p>}</div>{action}</header>{children}</section> }
function Empty({ title, children }: { title: string; children: ReactNode }) { return <div className={styles.empty}><CircleHelp size={20} aria-hidden="true" /><div><strong>{title}</strong><p>{children}</p></div></div> }
function Metric({ title, value, note }: { title: string; value: string; note: string }) { return <div className={styles.metric}><span>{title}</span><strong>{value}</strong><small>{note}</small></div> }
function SourceNote({ source }: { source: Pick<Source<unknown>, 'label' | 'state' | 'detail' | 'observedAt'> }) { return <div className={styles.sourceNote}><div><Radio size={14} /><strong>{source.label}</strong><Status value={source.state} /></div><p>{source.detail}{source.observedAt ? ` Observed ${date(source.observedAt)}.` : ''}</p></div> }
function Table({ headings, children }: { headings: string[]; children: ReactNode }) { return <div className={styles.tableScroll} tabIndex={0} role="region" aria-label={headings.join(', ')}><table><thead><tr>{headings.map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div> }
function Select({ name, title, value, options }: { name: string; title: string; value?: string; options: [string, string][] }) { return <label>{title}<select aria-label={title} name={name} defaultValue={value ?? ''}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label> }
function Filters({ data, params, section }: { data: GrowthData; params: URLSearchParams; section: Section }) {
  const { filters } = data, social = section === 'social', content = section === 'content'
  return <form className={styles.filters} method="get">
    {(social || content) && <label className={styles.search}>Search<input name="q" defaultValue={params.get('q') ?? ''} placeholder={social ? 'Title, hook or creative ID' : 'Topic, query or route'} type="search" /></label>}
    {!content && <><Select name="period" title={social ? 'Created' : 'Period'} value={filters.period} options={[['7', 'Last 7 days'], ['30', 'Last 30 days'], ['90', 'Last 90 days'], ['all', 'All available'], ['custom', 'Custom range']]} /><label>From<input name="from" type="date" defaultValue={filters.from} /></label><label>To<input name="to" type="date" defaultValue={filters.to} /></label></>}
    {!content && <Select name="game" title="Game" value={filters.game} options={[['', 'All games'], ...data.catalog.map(game => [game.slug, game.title] as [string, string])]} />}
    <Select name="locale" title="Locale" value={filters.locale} options={[['', 'All locales'], ['pt-br', 'PT-BR'], ['en', 'EN'], ['es-mx', 'ES-MX']]} />
    {social && <><Select name="reviewStatus" title="Review" value={params.get('reviewStatus') ?? ''} options={[['', 'All review states'], ...['draft', 'needs_review', 'approved', 'rejected'].map(s => [s, label(s)] as [string, string])]} /><Select name="platform" title="Platform" value={params.get('platform') ?? ''} options={[['', 'All platforms'], ['Universal vertical', 'Universal Shorts / Reels'], ['youtube', 'YouTube Shorts'], ['tiktok', 'TikTok'], ['instagram', 'Instagram Reels']]} /><Select name="renderStatus" title="Render" value={params.get('renderStatus') ?? ''} options={[['', 'All renders'], ['pending', 'Pending'], ['rendered', 'Rendered'], ['failed', 'Failed']]} /><Select name="uploadStatus" title="Upload" value={params.get('uploadStatus') ?? ''} options={[['', 'All upload states'], ...['not_uploaded', 'upload_pending', 'uploaded_private', 'uploaded_unlisted', 'uploaded_public', 'failed', 'historical_deleted'].map(s => [s, label(s)] as [string, string])]} /><Select name="publishStatus" title="Publish" value={params.get('publishStatus') ?? ''} options={[['', 'All publishing'], ['unpublished', 'Unpublished'], ['scheduled', 'Scheduled'], ['published', 'Published']]} /><Select name="sort" title="Sort" value={params.get('sort') ?? 'newest'} options={[['newest', 'Newest'], ['oldest', 'Oldest'], ['game', 'Game'], ['status', 'Review status']]} /></>}
    {section === 'overview' && <Select name="gameSort" title="Sort games" value={params.get('gameSort') ?? ''} options={[['', 'Game name'], ['clicks', 'Affiliate clicks'], ['creatives', 'Social creatives']]} />}
    {section === 'affiliate' && <><Select name="operator" title="Operator" value={filters.operator} options={[['', 'All operators'], ...data.operators.map(row => [row.id, row.name] as [string, string])]} /><Select name="placement" title="Placement" value={filters.placement} options={[['', 'All placements'], ...[...new Set(data.operators.flatMap(row => row.placements))].map(value => [value, label(value)] as [string, string])]} /><Select name="geo" title="Market" value={filters.geo} options={[['', 'All GEOs'], ['BR', 'Brazil'], ['MX', 'Mexico']]} /><Select name="device" title="Device" value={filters.device} options={[['', 'All devices'], ['mobile', 'Mobile'], ['desktop', 'Desktop']]} /><label>Source<input name="source" defaultValue={filters.source} placeholder="e.g. youtube" /></label></>}
    {['overview', 'affiliate', 'seo'].includes(section) && <label>Route<input name="route" defaultValue={filters.route} placeholder="/pt-br/play/crash" /></label>}
    {content && <><Select name="status" title="State" value={params.get('status') ?? ''} options={[['', 'All states'], ...CONTENT_STATES.map(s => [s, label(s)] as [string, string])]} /><Select name="type" title="Type" value={params.get('type') ?? ''} options={[['', 'All content'], ...[...new Set(data.content.map(row => row.type))].map(s => [s, s] as [string, string])]} /></>}
    <button type="submit" className={styles.primary}>Apply filters</button><Link className={styles.reset} href={`/owner/growth${section === 'overview' ? '' : `/${section}`}`} prefetch={false}>Reset</Link>
    {!social && !content && <small className={styles.filterHint}>Dates apply to measured data. Choose Custom range to use From/To. Inventory and historical audit states are current snapshots.</small>}
    {social && <small className={styles.filterHint}>Dates filter creative creation dates. Choose Custom range to use From/To. Review and upload states show the latest recorded status.</small>}
  </form>
}
function Pagination({ count, page, perPage, params, path }: { count: number; page: number; perPage: number; params: URLSearchParams; path: string }) {
  const pages = Math.max(1, Math.ceil(count / perPage)), link = (next: number) => { const copy = new URLSearchParams(params); copy.set('page', String(next)); copy.delete('creative'); return `${path}?${copy}` }
  return <div className={styles.pagination}><span>{count ? `${(page - 1) * perPage + 1}–${Math.min(page * perPage, count)} of ${count}` : '0 results'}</span><div>{page > 1 && <Link href={link(page - 1)} prefetch={false}>← Previous</Link>}<span>Page {page} of {pages}</span>{page < pages && <Link href={link(page + 1)} prefetch={false}>Next →</Link>}</div></div>
}
function TrafficSnapshot({ data }: { data: GrowthData }) {
  const snapshot = data.trafficSnapshot
  return <Panel title="Latest observed traffic" sub={`Vercel production · ${snapshot.periodLabel}`} action={<Badge tone="blue">Manual snapshot · 27 Sep</Badge>}><div className={styles.snapshotStats}><Metric title="Visitors" value={n(snapshot.visitors)} note="Vercel visitor metric" /><Metric title="Page views" value={n(snapshot.pageViews)} note="Completed 30-day report" /><Metric title="Bounce rate" value={percent(snapshot.bounceRate)} note="Vercel reported rate" /></div><div className={styles.twoColumns}><Table headings={['Top pages', 'Visitors']}>{snapshot.topPagesByVisitors.map(row => <tr key={row.route}><td>{row.route}</td><td>{n(row.visitors)}</td></tr>)}</Table><Table headings={['Referrer', 'Visitors']}>{snapshot.referrersByVisitors.map(row => <tr key={row.source}><td>{row.source}</td><td>{n(row.visitors)}</td></tr>)}</Table></div><p className={styles.inlineNote}>{snapshot.note} This fixed snapshot is independent of the report filters above.</p></Panel>
}
function ManualSearchSnapshot({ data }: { data: GrowthData }) {
  const snapshot = data.searchSnapshot
  return <Panel title="Latest observed Search Console performance" sub={`${snapshot.periodLabel} · Web search · inspected 27 Sep 2026`} action={<Badge tone="blue">Manual snapshot</Badge>}><div className={styles.miniMetrics}><Metric title="Clicks" value={n(snapshot.clicks)} note="Google property total" /><Metric title="Impressions" value={n(snapshot.impressions)} note="Google property total" /><Metric title="CTR" value={percent(snapshot.ctr)} note="Google displayed rate" /><Metric title="Average position" value={snapshot.position.toFixed(1)} note="Google displayed average" /></div><details><summary>View observed queries and landing pages</summary><Table headings={['Query', 'Clicks', 'Impressions', 'CTR', 'Position']}>{snapshot.queries.map(row => <tr key={row.query}><td>{row.query}</td><td>{row.clicks}</td><td>{row.impressions}</td><td>{percent(row.ctr)}</td><td>{row.position}</td></tr>)}</Table><Table headings={['Page', 'Clicks', 'Impressions', 'CTR', 'Position']}>{snapshot.pages.map(row => <tr key={row.page}><td>{new URL(row.page).pathname}</td><td>{row.clicks}</td><td>{row.impressions}</td><td>{percent(row.ctr)}</td><td>{row.position}</td></tr>)}</Table></details><p className={styles.inlineNote}>{snapshot.note} This fixed snapshot is independent of the reporting filters above. No displayed row meets the 100-impression opportunity threshold.</p></Panel>
}
function Overview({ data }: { data: GrowthData }) {
  const { social, metrics, search } = data, count = (state: string) => social.data.filter(item => item.reviewStatus === state).length
  return <><GenerationPanel data={data} /><TrafficSnapshot data={data} />
    <div className={styles.metrics}><Metric title="Page views" value={n(metrics?.visits)} note={metrics ? 'Recorded page-view events' : 'Analytics not connected'} /><Metric title="Completed gameplay cycles" value={n(metrics?.cycles)} note={metrics ? 'Consented event count' : 'Event reporting not connected'} /><Metric title="Affiliate clicks" value={n(metrics?.clicks)} note={metrics ? `${percent(metrics.ctr)} impression-to-click rate` : 'Reporting not connected'} /><Metric title="Creative library" value={n(social.data.length)} note={`${count('needs_review')} need review · ${count('approved')} approved`} /></div>
    <div className={styles.twoColumns}><Panel title="Today’s priorities" sub="Actions supported by the records available here."><div className={styles.priority}><span className={styles.priorityIcon}><Clapperboard size={19} /></span><div><strong>{count('needs_review')} creatives need review</strong><p>The imported PT-BR library is ready for metadata review. Media from the old workstation is unavailable here.</p></div><Link aria-label="Open creative review queue" href="/owner/growth/social?reviewStatus=needs_review"><ArrowUpRight size={20} /></Link></div><div className={styles.priority}><span className={styles.priorityIcon}><Search size={19} /></span><div><strong>{data.indexing.filter(row => row.state === 'Requested').length} indexing requests accepted in the audit</strong><p>Acceptance is recorded separately from indexing. Open SEO for page-level evidence.</p></div><Link aria-label="Open indexing audit" href="/owner/growth/seo"><ArrowUpRight size={20} /></Link></div><div className={styles.priority}><span className={styles.priorityIcon}><FileText size={19} /></span><div><strong>{data.content.filter(row => row.type === 'Social opportunity').length} Originals have no Short in this library</strong><p>Coverage gaps are available as content opportunities. Generated batches appear in Social.</p></div><Link aria-label="Open content opportunities" href="/owner/growth/content?status=opportunity"><ArrowUpRight size={20} /></Link></div></Panel>
    <Panel title="Data connections" sub="Missing reporting stays visible; missing metrics stay empty."><SourceNote source={data.analytics} /><SourceNote source={search} /><SourceNote source={social} /><p className={styles.inlineNote}>YouTube {data.youtubeReady ? 'credentials available for read-only sync' : 'not connected'} · TikTok not connected · Instagram not connected</p></Panel></div>
    <Panel title="PlayLiva funnel" sub="Consented event counts, not a unique-user or attributed conversion cohort."><div className={styles.funnel}>{[['Page view', metrics?.visits], ['Game start', metrics?.starts], ['Completed cycle', metrics?.cycles], ['Offer impression', metrics?.impressions], ['Affiliate click', metrics?.clicks]].map(([title, value], index) => <div key={String(title)}><small>0{index + 1}</small><span>{title}</span><strong>{n(value as number | undefined)}</strong></div>)}</div>{!metrics && <p className={styles.inlineNote}>Event reporting is not connected for this date range. No conversion rates are inferred.</p>}<p className={styles.inlineNote}>Unique visitors, organic sessions, social sessions, FTD and revenue: not connected.</p></Panel>
    <Panel title="Performance by game" sub={`${data.catalog.length} Originals from the existing PlayLiva catalog. Social counts cover the whole imported library.`}><Table headings={['Game', 'Page views', 'Starts', 'Cycles', 'Impressions', 'Clicks', 'CTR', 'Creatives', 'SEO clicks', 'SEO impressions', 'Top SEO locale']}>{data.games.map(game => <tr key={game.id}><td><div className={styles.gameCell}><Image src={game.poster} alt="" width={52} height={38} /><div><strong>{game.title}</strong><small>{game.category}</small></div></div></td><td>{n(game.metrics?.visits)}</td><td>{n(game.metrics?.starts)}</td><td>{n(game.metrics?.cycles)}</td><td>{n(game.metrics?.impressions)}</td><td>{n(game.metrics?.clicks)}</td><td>{percent(game.metrics?.ctr)}</td><td>{game.creatives}</td><td>{n(game.seoClicks)}</td><td>{n(game.seoImpressions)}</td><td>{game.topLocale?.toUpperCase() ?? '—'}</td></tr>)}</Table></Panel>
    <div className={styles.twoColumns}><Panel title="Search at a glance"><div className={styles.miniMetrics}><Metric title="Search clicks" value={n(search.data.clicks)} note="Google Search Console" /><Metric title="Impressions" value={n(search.data.impressions)} note="Google Search Console" /><Metric title="CTR" value={percent(search.data.ctr)} note="Search click-through rate" /><Metric title="Average position" value={search.data.position?.toFixed(1) ?? '—'} note="Final Google data" /></div><p className={styles.inlineNote}>Top query: {search.data.queries[0]?.query || 'Not connected'}<br />Top search page: {search.data.pages[0]?.page || 'Not connected'}</p></Panel><ActivityLog data={data} /></div>
  </>
}
function ActivityLog({ data, target }: { data: GrowthData; target?: string }) {
  const rows = data.activity.filter(row => !target || row.target === target)
  return <Panel title="Owner activity" sub="Persistent decisions and workflow events.">{rows.length ? <ol className={styles.activity}>{rows.map(row => <li key={row.id}><span /><div><strong>{label(row.action)}</strong><small>{row.target} · {date(row.at)}</small><p>{row.detail}</p></div></li>)}</ol> : <Empty title="No owner actions recorded yet">Approvals, rejections, regeneration requests, content changes and YouTube syncs will appear here.</Empty>}</Panel>
}
async function CreativeReview({ item, data }: { item: Creative; data: GrowthData }) {
  const creative = await withMedia(item), jobs = data.jobs.filter(job => job.creativeId === item.id)
  return <section className={styles.review} aria-label="Creative review"><header className={styles.reviewHeading}><div><p className={styles.eyebrow}>CREATIVE REVIEW</p><h2>{creative.title}</h2><small>{creative.id}</small></div><Link href="/owner/growth/social" prefetch={false}>Close review ×</Link></header><div className={styles.reviewColumns}><div className={styles.preview}>{creative.media.video ? <VideoPreview id={creative.id} thumbnail={creative.media.thumbnail} /> : <Empty title="Video unavailable on this computer">The master remains on the old workstation. Recorded QC is preserved; no replacement was generated.</Empty>}{creative.media.thumbnail && <Image src={`/api/owner/media/${creative.id}/thumbnail`} alt={`Thumbnail for ${creative.title}`} width={270} height={480} />}</div><div className={styles.reviewBody}><div className={styles.badgeRow}><Status value={creative.reviewStatus} /><Status value={creative.renderStatus} /><Status value={creative.uploadStatus} /><Status value={creative.publishStatus} /></div><h3>{creative.hook}</h3><p lang={creative.locale}>{creative.caption}</p><p lang={creative.locale}>{creative.description}</p><p className={styles.muted}>{creative.hashtags.join(' ')}</p><dl className={styles.details}>{[['Game', creative.gameTitle], ['Platform / locale', `${creative.platform} · ${creative.locale}`], ['Duration', `${creative.duration} seconds`], ['Created / updated', `${date(creative.createdAt)} / ${date(creative.updatedAt)}`], ['Approved', date(creative.approvedAt)], ['UTM campaign', creative.utmCampaign], ['UTM content', creative.utmContent], ['YouTube ID', creative.youtube.videoId || 'None recorded'], ['Current YouTube state', label(creative.youtube.state)], ['Evidence', creative.youtube.source]].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p className={styles.inlineNote}>YouTube views {n(creative.youtube.views)} · likes {n(creative.youtube.likes)} · comments {n(creative.youtube.comments)}. UTM sessions and affiliate clicks: not connected.</p>
    <details><summary>Technical QC and upload history</summary>{creative.qc ? <p>{creative.qc.width} × {creative.qc.height} · {creative.qc.fps} fps · {creative.qc.bitrate} kbps · {creative.qc.lufs} LUFS<br />QC {creative.qc.passed ? 'passed' : 'failed'} on {date(creative.qc.inspectedAt)}. {creative.qc.notes.join(' ') || 'No QC notes.'}</p> : <p>No recorded technical QC.</p>}{creative.uploadHistory.length ? creative.uploadHistory.map(row => <p key={row.videoId}>{row.videoId} · {label(row.state)} · uploaded {date(row.uploadedAt)}<br />{row.source}</p>) : <p>No per-ID upload history in this checkout.</p>}</details>
    <GeneratedActions id={creative.id} data={data} /><div className={styles.reviewActions}><ActionForm endpoint={`/api/owner/social/${creative.id}`}><input type="hidden" name="action" value="approve" /><label className={styles.checkbox}><input type="checkbox" name="reviewed" required /> I have reviewed this creative. Approval does not authorize upload.</label><button type="submit" className={styles.primary} disabled={!creative.qc?.passed || jobs.some(job => ['queued', 'running'].includes(job.state))}>Approve creative</button></ActionForm><ActionForm endpoint={`/api/owner/social/${creative.id}`}><input type="hidden" name="action" value="reject" /><label>Rejection reason (optional)<input name="reason" maxLength={240} placeholder="What needs to change?" /></label><button type="submit">Reject creative</button></ActionForm>{!data.automation.jobs.some(row => row.id === creative.id) && <ActionForm endpoint={`/api/owner/social/${creative.id}`} confirm="Queue this one creative for workstation regeneration? This clears review approval. It does not start a render, upload or publish anything."><input type="hidden" name="action" value="regenerate" /><button type="submit">Queue regeneration</button><small>Workstation execution required. Historical workstation workflow only.</small></ActionForm>}</div>{jobs.map(job => <p key={job.id}><Status value={job.state} /> {job.detail}</p>)}</div></div><ActivityLog data={data} target={creative.id} /></section>
}
async function Social({ data, params }: { data: GrowthData; params: URLSearchParams }) {
  const items = filterCreatives(data.social.data, params, data.filters).filter(item => !params.get('batch') || item.id.startsWith(`${params.get('batch')}-`)), page = Math.max(1, Math.min(Number(params.get('page')) || 1, Math.max(1, Math.ceil(items.length / 12))))
  const visible = await Promise.all(items.slice((page - 1) * 12, page * 12).map(withMedia)), selected = data.social.data.find(item => item.id === params.get('creative'))
  const count = (field: keyof Creative, value: string) => data.social.data.filter(item => item[field] === value).length
  return <><GenerationPanel data={data} /><div className={styles.metrics}><Metric title="All creatives" value={n(data.social.data.length)} note="Imported PT-BR metadata" /><Metric title="Needs review" value={n(count('reviewStatus', 'needs_review'))} note={`${count('reviewStatus', 'approved')} approved · ${count('reviewStatus', 'rejected')} rejected`} /><Metric title="Current private uploads" value={n(count('uploadStatus', 'uploaded_private'))} note="Owner-confirmed; not a live check" /><Metric title="Published" value={n(count('publishStatus', 'published'))} note="Recorded state; publishing disabled" /></div>
    <div className={styles.notice}><ShieldCheck size={20} /><div><strong>Historical uploads reconciled without rewriting history</strong><p>Owner-confirmed on 27 Sep 2026: Island Crash 10 (<code>l1x4jFmamyw</code>) is the one remaining private upload. Nine other historical uploads were deleted. Their IDs and upload dates remain on the old computer and are unavailable here. The separate archived proof-of-concept record is not counted as a current upload.</p></div></div>
    <div className={styles.platforms}><span>YouTube <Status value={data.youtubeReady ? 'connected' : 'not_connected'} /></span><span>TikTok <Status value="not_connected" /></span><span>Instagram <Status value="not_connected" /></span><ActionForm endpoint="/api/owner/youtube/sync"><button type="submit" disabled={!data.youtubeReady}>Sync YouTube state</button></ActionForm></div>
    {selected && <CreativeReview item={selected} data={data} />}
    <Panel title="Shorts library" sub="Inventory filters apply to all creatives. No video bytes load in this list." action={<Badge>{items.length} results</Badge>}>
      {visible.length ? <div className={styles.creativeGrid}>{visible.map(item => { const poster = data.catalog.find(game => game.slug === item.gameSlug)?.poster; const link = new URLSearchParams(params); link.set('creative', item.id); return <Link key={item.id} className={styles.creativeCard} prefetch={false} href={`/owner/growth/social?${link}#owner-main`}><div className={styles.thumbnail}>{item.media.thumbnail ? <Image src={`/api/owner/media/${item.id}/thumbnail`} alt={`Creative thumbnail: ${item.title}`} width={120} height={180} /> : poster ? <Image src={poster} alt="Game artwork; creative thumbnail unavailable" width={120} height={180} /> : <Clapperboard size={28} />}<span>{item.duration}s</span>{!item.media.thumbnail && <small>Game artwork</small>}</div><div className={styles.creativeInfo}><small>{item.gameTitle} · {item.locale}</small><h3 lang={item.locale}>{item.title}</h3><p lang={item.locale}>{item.hook}</p><code>{item.id}</code><div className={styles.badgeRow}><Status value={item.reviewStatus} /><Status value={item.uploadStatus} /><Status value={item.publishStatus} /></div><small>{item.platform === 'Universal vertical' ? 'Universal Shorts / Reels' : 'YouTube Shorts'} · QC {item.qc?.passed ? 'passed' : 'unverified'} · {date(item.createdAt)}</small><small>{item.media.video ? 'Master available' : 'Media unavailable · metadata preserved'} · {label(item.renderStatus)}</small></div></Link> })}</div> : <Empty title="No creatives match these filters">Reset or adjust the filters. Disconnected platforms have no fabricated content.</Empty>}
      <Pagination count={items.length} page={page} perPage={12} params={params} path="/owner/growth/social" /></Panel><div className={styles.twoColumns}><Panel title="Regeneration queue" sub="Durable requests for the existing local rendering workflow.">{data.jobs.length ? data.jobs.map(job => <div className={styles.queueRow} key={job.id}><strong>{job.creativeId}</strong><Status value={job.state} /><p>{job.detail}</p></div>) : <Empty title="No pending regeneration requests">Queue a single creative from its review view. Rendering requires the workstation worker and original runtime.</Empty>}</Panel><ActivityLog data={data} /></div>
  </>
}
function Seo({ data }: { data: GrowthData }) {
  const { search, filters } = data, audit = data.indexing.filter(row => (!filters.locale || row.locale === filters.locale) && (!filters.game || row.route.endsWith(`/play/${filters.game}`)) && (!filters.route || row.route === filters.route))
  return <><ManualSearchSnapshot data={data} />{['connected', 'no_data'].includes(search.state) && <div className={styles.metrics}><Metric title="Search clicks" value={n(search.data.clicks)} note="Google Search Console" /><Metric title="Search impressions" value={n(search.data.impressions)} note="Final Google performance data" /><Metric title="CTR" value={percent(search.data.ctr)} note="Search click-through rate" /><Metric title="Average position" value={search.data.position?.toFixed(1) ?? '—'} note="Not inferred from indexing" /></div>}<SourceNote source={search} />
    <div className={styles.twoColumns}><Panel title="Top queries">{search.data.queries.length ? <Table headings={['Query', 'Clicks', 'Impressions', 'CTR', 'Position']}>{search.data.queries.slice(0, 25).map((row, i) => <tr key={i}><td>{row.query}</td><td>{n(row.clicks)}</td><td>{n(row.impressions)}</td><td>{percent(row.ctr)}</td><td>{row.position.toFixed(1)}</td></tr>)}</Table> : <Empty title="Search query data not connected">Query metrics require a server-side read connection to Search Console. Manual URL inspection is not a performance feed.</Empty>}</Panel><Panel title="Top landing pages">{search.data.pages.length ? <Table headings={['Page', 'Clicks', 'Impressions', 'Position']}>{search.data.pages.slice(0, 25).map(row => <tr key={row.page}><td>{new URL(row.page).pathname}</td><td>{n(row.clicks)}</td><td>{n(row.impressions)}</td><td>{row.position.toFixed(1)}</td></tr>)}</Table> : <Empty title="Landing-page metrics unavailable">PT-BR, EN and ES-MX routes are in the inventory. Their traffic is not assumed.</Empty>}</Panel></div>
    <Panel title="Evidence-based opportunities" sub="Rules evaluate at least 100 impressions. Every recommendation must include measured evidence.">{data.opportunities.length ? data.opportunities.map(item => <div className={styles.priority} key={item.id}><div><strong>{item.topic}</strong><p>{item.reason}</p><small>{item.action}</small></div></div>) : <Empty title="No measured SEO opportunities yet">Connect performance data to evaluate low CTR, positions 4–15 and landing-page gaps. Rising-query and weak-link rules require their additional comparison evidence.</Empty>}</Panel>
    <Panel title="Indexing watchlist" sub="Historical production audit · 27 Sep 2026 · 7 recent Originals × 3 locales"><div className={styles.inlineNote}>An accepted indexing request does not mean a page is indexed. The rows below are dated observations, not live Google status.</div><Table headings={['Canonical page', 'Locale', 'Observed state', 'Indexing request', 'Sitemap']}>{audit.map(row => <tr key={row.url}><td><a href={row.url} target="_blank" rel="noreferrer">{row.topic} ↗</a><small>{row.route}</small><small>{row.detail}</small></td><td>{row.locale.toUpperCase()}</td><td><Status value={row.state} /></td><td>{row.request}</td><td>Included</td></tr>)}</Table></Panel>
    <Panel title="Sitemap record"><div className={styles.sitemap}><div><strong>{data.searchAudit.sitemap.url}</strong><p>Submission accepted: {data.searchAudit.sitemap.submitted} · reported status: {data.searchAudit.sitemap.tableStatus}</p><p>Google’s recorded last read: {data.searchAudit.sitemap.lastRead} · discovered pages then: {data.searchAudit.sitemap.discoveredPages}</p></div><Badge tone="blue">Historical snapshot</Badge></div><p className={styles.inlineNote}>{data.searchAudit.provenance} Current source inventory contains {data.content.filter(row => row.source === 'Public sitemap configuration').length} routes. Discovery counts and source counts describe different things.</p></Panel>
  </>
}
function Affiliate({ data }: { data: GrowthData }) {
  const m = data.metrics
  return <><div className={styles.metrics}><Metric title="Offer impressions" value={n(m?.impressions)} note="Affiliate + campaign impression events" /><Metric title="Affiliate clicks" value={n(m?.clicks)} note="Consented click events" /><Metric title="Impression-to-click rate" value={percent(m?.ctr)} note="Comparable observed events only" /><Metric title="Recurring offer exposure" value={n(m?.popupImpressions)} note={`${n(m?.popupClicks)} recorded popup clicks`} /></div><SourceNote source={data.analytics} /><div className={styles.notice}><ShieldCheck size={20} /><div><strong>Measurement ends at the affiliate click</strong><p>FTD, CPA, RevShare, commission and revenue data are not connected. Operator configuration is not proof of traffic or earnings. The existing 3 / 6 / 9 gameplay cadence and GEO eligibility are unchanged.</p></div></div>
    <Panel title="Operator configuration" sub="Read directly from current partner and campaign configuration. No destinations are disclosed here."><Table headings={['Operator', 'Partnership', 'Eligible GEO', 'Destination', 'Campaign / placements', 'Tracking health']}>{data.operators.map(row => <tr key={row.id}><td><strong>{row.name}</strong><small>Verified {date(row.verifiedAt)}</small></td><td><Status value={row.status} /></td><td>{row.eligibleGeo.join(', ') || 'None currently eligible'}</td><td>{row.destinationConfigured ? 'Configured' : 'Not configured'}</td><td>{row.campaign || 'No active campaign'}<small>{row.placements.map(label).join(' · ')}</small>{row.campaignReviewBy && <small>Review by {row.campaignReviewBy}</small>}</td><td>{row.destinationConfigured ? 'Configuration present; delivery reporting not connected' : 'Not connected'}</td></tr>)}</Table></Panel>
    <div className={styles.twoColumns}>{Object.entries(data.groups).map(([dimension, rows]) => <Panel key={dimension} title={`By ${dimension}`} sub="Current selected period and filters.">{rows.length && data.measured ? <Table headings={[label(dimension), 'Impressions', 'Clicks', 'CTR']}>{rows.slice(0, 20).map(row => <tr key={row.value}><td>{row.value}</td><td>{n(row.impressions)}</td><td>{n(row.clicks)}</td><td>{percent(row.ctr)}</td></tr>)}</Table> : <Empty title="No reporting source connected">No measured {dimension} ranking is available for this period.</Empty>}</Panel>)}</div>
  </>
}
function Content({ data, params }: { data: GrowthData; params: URLSearchParams }) {
  const query = (params.get('q') ?? '').toLowerCase(), edit = data.content.find(item => item.id === params.get('edit'))
  const items = data.content.filter(row => (!data.filters.locale || row.locale === data.filters.locale) && (!params.get('status') || row.status === params.get('status')) && (!params.get('type') || row.type === params.get('type')) && `${row.topic} ${row.query} ${row.route}`.toLowerCase().includes(query))
  const page = Math.max(1, Math.min(Number(params.get('page')) || 1, Math.max(1, Math.ceil(items.length / 25))))
  return <><div className={styles.lifecycle}>{CONTENT_STATES.map(status => <Link key={status} href={`/owner/growth/content?status=${status}`} prefetch={false}><span>{label(status)}</span><strong>{data.content.filter(row => row.status === status).length}</strong></Link>)}</div><Panel title={edit ? `Update plan: ${edit.topic}` : 'Plan the next piece'} sub="A lightweight editorial record. Saving never publishes or modifies public pages."><details open={Boolean(edit)} key={edit?.id || 'new'}><summary>{edit ? 'Edit content plan' : 'Add a content idea'}</summary><ActionForm endpoint="/api/owner/content">{edit && <input type="hidden" name="id" value={edit.id} />}<div className={styles.contentForm}><label>Topic<input name="topic" required maxLength={240} defaultValue={edit?.topic} /></label><Select name="locale" title="Locale" value={edit?.locale || 'pt-br'} options={[['pt-br', 'PT-BR'], ['en', 'EN'], ['es-mx', 'ES-MX']]} /><Select name="status" title="State" value={edit?.status || 'idea'} options={CONTENT_STATES.map(status => [status, label(status)])} /><label>Type<input name="type" defaultValue={edit?.type || 'Editorial plan'} maxLength={60} /></label><label>Intent / query<input name="query" defaultValue={edit?.query} maxLength={240} /></label><label>Target route<input name="route" defaultValue={edit?.route} placeholder="/pt-br/..." maxLength={240} /></label><label className={styles.wide}>Priority reason<textarea name="reason" defaultValue={edit?.reason} maxLength={500} rows={2} /></label></div><button className={styles.primary} type="submit">Save content plan</button></ActionForm></details></Panel><Panel title="Content inventory & pipeline" sub="Existing pages come from the sitemap. Planned work and status changes stay in owner storage."><Table headings={['Topic / route', 'Type', 'Locale', 'State', 'Priority reason', 'Last updated', 'Action']}>{items.slice((page - 1) * 25, page * 25).map(row => <tr key={row.id}><td><strong>{row.topic}</strong><small>{row.route || 'Route not planned yet'}</small>{row.query && <small>Intent: {row.query}</small>}</td><td>{row.type}</td><td>{row.locale.toUpperCase()}</td><td><Status value={row.status} /></td><td>{row.reason}</td><td>{date(row.updatedAt)}</td><td><Link prefetch={false} href={`/owner/growth/content?edit=${row.id}`}>Edit plan</Link></td></tr>)}</Table>{!items.length && <Empty title="No content matches these filters">Create a plan or adjust the filters. Empty stages contain no invented drafts.</Empty>}<Pagination count={items.length} page={page} perPage={25} params={params} path="/owner/growth/content" /></Panel></>
}
export async function GrowthPage({ section, searchParams }: { section: Section; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams, params = new URLSearchParams(Object.entries(raw).flatMap(([key, value]) => typeof value === 'string' ? [[key, value]] : []))
  let data: GrowthData
  try { data = await growthData(params) } catch (error) { if (error instanceof Error && error.message === 'Start date must be before the end date.') return <Empty title="Invalid date range">The start date must be before the end date. <Link href="/owner/growth">Reset filters</Link></Empty>; throw error }
  return <div className={styles.page} data-owner-section={section}><header className={styles.pageHeader}><div><p className={styles.eyebrow}>OWNER GROWTH / {section.toUpperCase()}</p><h1>{headings[section][0]}</h1><p>{headings[section][1]}</p></div><Badge tone="blue">{data.persistence === 'local_filesystem' ? 'Local review' : 'Owner workspace'}</Badge></header>{data.persistenceError && <div className={styles.error}>Owner persistence is unavailable. Try again before making review decisions.</div>}<Filters data={data} params={params} section={section} />{section === 'overview' ? <Overview data={data} /> : section === 'social' ? <Social data={data} params={params} /> : section === 'seo' ? <Seo data={data} /> : section === 'affiliate' ? <Affiliate data={data} /> : <Content data={data} params={params} />}</div>
}
