import type { Locale } from '@/lib/types'

const copy = {
  'pt-BR': {
    title: 'Avia de Janeiro — Jogo crash grátis sobre o Rio',
    description: 'Decole sobre uma baía inspirada no Rio em Avia de Janeiro. Retire antes do fim do voo ou escolha a retirada automática. Original grátis com créditos virtuais.',
    betting: 'EMBARQUE ABERTO', flying: 'RIO, LÁ VAMOS NÓS', result: 'FIM DO VOO',
    countdown: 'Decolagem em', stake: 'Créditos por voo', auto: 'Retirada automática', off: 'Desligada',
    bet: 'Embarcar neste voo', booked: 'Embarque confirmado', cashout: 'Retirar agora', cashed: 'Retirada confirmada',
    watching: 'Acompanhe o voo', next: 'Próximo embarque em instantes', held: 'Próximo voo após fechar a oferta',
    current: 'Neste voo', draft: 'Alterações valem para o próximo embarque.',
    invalid: 'Use 1 a 50 créditos. A retirada automática deve ficar entre 1,01× e 100,00×.',
    unavailable: 'Conexão interrompida. Reconectando; a rodada continua no servidor. A retirada automática permanece ativa.',
    rejected: 'A ação não chegou a tempo ou os créditos são insuficientes. Confira o resultado confirmado.',
    syncing: 'Conectando à torre…', pending: 'Confirmando…', history: 'Últimos voos', coast: 'Baía do Rio · voo livre',
    rulesTitle: 'Como jogar Avia de Janeiro', creditsTitle: 'Diversão com créditos virtuais',
    credits: 'Jogo gratuito de entretenimento. Liva Credits não têm valor monetário, não podem ser comprados ou sacados e não representam dinheiro real.',
    paragraphs: [
      'O céu dourado, a faixa de areia e as montanhas junto à baía dão o cenário de Avia de Janeiro. Neste PlayLiva Original, um avião esportivo voa sozinho enquanto o multiplicador sobe: sua decisão é quando retirar os créditos da rodada. Não há direção, toques para manter o voo ou controle de velocidade.',
      'Os voos se sucedem automaticamente. Embarque durante a contagem regressiva, acompanhe a decolagem e retire antes do fim do voo. Uma retirada bem-sucedida encerra apenas sua participação; o avião continua até o ponto de crash daquela rodada. Observar sem embarcar não gasta créditos.',
      'Prefere definir um limite antes de decolar? Ative a retirada automática e digite seu multiplicador. O limite confirmado fica visível durante o voo e é resolvido pelo servidor mesmo se a conexão cair. A paisagem e a aceleração não são pistas do resultado, e nenhum multiplicador futuro é garantido.',
    ],
    rules: [
      'Escolha de 1 a 50 créditos e confirme o embarque antes de a contagem terminar. Cada voo aceita uma participação; o valor é descontado uma única vez.',
      'O multiplicador começa em 1,00× e cresce sozinho. Retire manualmente antes do crash. O horário em que o servidor processa a ação decide a retirada; atrasos de rede contam. No instante exato do crash, a retirada perde.',
      'A retirada automática aceita 1,01× a 100,00×. O limite é fixado no embarque e só ganha se for estritamente menor que o ponto de crash. Alterar o campo depois não modifica a rodada atual.',
      'Retorno = créditos usados × multiplicador da retirada, arredondado para baixo a 0,01 crédito. Sem retirada válida, perde-se o valor usado. O voo continua após sua retirada.',
      'A curva demo utiliza o mesmo sorteio criptográfico dos jogos crash PlayLiva: margem matemática de 3% e teto de 100×. Não há certificação ou promessa de lucro. Animação e áudio não alteram o sorteio.',
      'Recarregar reconecta à rodada do servidor, sem nova aposta nem pagamento duplicado. Sem conexão, a retirada manual não funciona; a automática mantém o limite confirmado. Os créditos continuam locais a este navegador, compartilhados com os outros Originals. Redefinir o saldo fica disponível fora da rodada.',
    ],
  },
  en: {
    title: 'Avia de Janeiro — Free Rio flight crash game',
    description: 'Fly over a Rio-inspired bay in Avia de Janeiro. Cash out before the flight ends or set an automatic target. A free PlayLiva Original with virtual credits.',
    betting: 'BOARDING OPEN', flying: 'RIO, HERE WE GO', result: 'FLIGHT ENDED',
    countdown: 'Takeoff in', stake: 'Credits per flight', auto: 'Auto cashout', off: 'Off',
    bet: 'Board this flight', booked: 'Boarding confirmed', cashout: 'Cash out now', cashed: 'Cashout confirmed',
    watching: 'Watch the flight', next: 'Next boarding shortly', held: 'Next flight after closing the offer',
    current: 'This flight', draft: 'Edits apply to your next boarding.',
    invalid: 'Use 1–50 credits. Auto cashout must be between 1.01× and 100.00×.',
    unavailable: 'Connection interrupted. Reconnecting; the round continues on the server. Auto cashout stays active.',
    rejected: 'The action arrived too late or credits were insufficient. Check the confirmed result.',
    syncing: 'Connecting to the tower…', pending: 'Confirming…', history: 'Recent flights', coast: 'Rio bay · free flight',
    rulesTitle: 'How to play Avia de Janeiro', creditsTitle: 'Entertainment with virtual credits',
    credits: 'Free entertainment only. Liva Credits have no monetary value, cannot be bought or withdrawn and do not represent real money.',
    paragraphs: [
      'A golden sky, a ribbon of sand and mountains beside the bay set the scene for Avia de Janeiro. In this PlayLiva Original, a sporty aircraft flies by itself while the multiplier rises. Your decision is when to cash out your round’s credits. There is no steering, tapping to keep flying or speed control.',
      'Flights run in a continuous cycle. Board during the countdown, watch the takeoff and cash out before the flight ends. A successful cashout settles only your wager; the aircraft continues to that round’s crash point. Watching without boarding costs no credits.',
      'Prefer to set a target before takeoff? Enable auto cashout and enter a multiplier. Your confirmed target stays visible during flight and the server resolves it even if the connection drops. Scenery and acceleration do not predict the outcome, and no future multiplier is guaranteed.',
    ],
    rules: [
      'Choose 1–50 credits and confirm boarding before the countdown ends. One wager per flight; credits are deducted exactly once.',
      'The multiplier starts at 1.00× and rises automatically. Cash out before the crash. Server processing time decides manual cashout, so network delay matters. A cashout at the exact crash deadline loses.',
      'Auto cashout accepts 1.01×–100.00×. The target is fixed when boarding and wins only if strictly below the crash point. Editing the field later does not change the current wager.',
      'Return = credits played × cashout multiplier, rounded down to 0.01 credit. Without a valid cashout, your stake is lost. Flight continues after cashout.',
      'The demo curve reuses PlayLiva’s cryptographic crash draw with a mathematical 3% edge and a 100× cap. This is not certified or a profit promise. Animation and audio do not affect the draw.',
      'Reloading reconnects to the server round without another wager or duplicate return. Manual cashout needs a connection; auto cashout retains its confirmed target. Credits remain local to this browser and shared with other Originals. Balance reset is available outside a round.',
    ],
  },
  'es-MX': {
    title: 'Avia de Janeiro — Juego crash gratis sobre Río',
    description: 'Vuela sobre una bahía inspirada en Río en Avia de Janeiro. Retira antes del final o fija un retiro automático. Original gratis con créditos virtuales.',
    betting: 'EMBARQUE ABIERTO', flying: 'RÍO, ALLÁ VAMOS', result: 'FIN DEL VUELO',
    countdown: 'Despegue en', stake: 'Créditos por vuelo', auto: 'Retiro automático', off: 'Desactivado',
    bet: 'Abordar este vuelo', booked: 'Embarque confirmado', cashout: 'Retirar ahora', cashed: 'Retiro confirmado',
    watching: 'Sigue el vuelo', next: 'Próximo embarque en breve', held: 'Próximo vuelo al cerrar la oferta',
    current: 'Este vuelo', draft: 'Los cambios aplican al próximo embarque.',
    invalid: 'Usa de 1 a 50 créditos. El retiro automático debe estar entre 1.01× y 100.00×.',
    unavailable: 'Conexión interrumpida. Reconectando; la ronda sigue en el servidor. El retiro automático permanece activo.',
    rejected: 'La acción llegó tarde o los créditos no alcanzan. Revisa el resultado confirmado.',
    syncing: 'Conectando con la torre…', pending: 'Confirmando…', history: 'Últimos vuelos', coast: 'Bahía de Río · vuelo libre',
    rulesTitle: 'Cómo jugar Avia de Janeiro', creditsTitle: 'Diversión con créditos virtuales',
    credits: 'Solo entretenimiento gratuito. Los Liva Credits no tienen valor monetario, no se compran ni retiran y no representan dinero real.',
    paragraphs: [
      'El cielo dorado, una franja de arena y las montañas junto a la bahía dan identidad a Avia de Janeiro. En este PlayLiva Original, una aeronave deportiva vuela sola mientras sube el multiplicador. Tú decides cuándo retirar los créditos de la ronda. No hay dirección, toques para seguir volando ni control de velocidad.',
      'Los vuelos se suceden automáticamente. Aborda durante la cuenta regresiva, observa el despegue y retira antes del final. Un retiro exitoso liquida solo tu participación; el avión sigue hasta el punto de crash de esa ronda. Observar sin abordar no cuesta créditos.',
      '¿Prefieres fijar un límite antes del despegue? Activa el retiro automático y escribe un multiplicador. El límite confirmado permanece visible durante el vuelo y el servidor lo resuelve aunque se corte la conexión. El paisaje y la aceleración no anticipan el resultado; ningún multiplicador futuro está garantizado.',
    ],
    rules: [
      'Elige de 1 a 50 créditos y confirma el embarque antes del final de la cuenta regresiva. Cada vuelo admite una participación; los créditos se descuentan una sola vez.',
      'El multiplicador empieza en 1.00× y sube automáticamente. Retira antes del crash. Decide el momento en que el servidor procesa la acción; el retraso de red cuenta. Un retiro en el instante exacto del crash pierde.',
      'El retiro automático acepta de 1.01× a 100.00×. Se fija al abordar y solo gana si es estrictamente menor al punto de crash. Cambiar el campo después no modifica la participación actual.',
      'Retorno = créditos usados × multiplicador de retiro, redondeado hacia abajo a 0.01 crédito. Sin retiro válido se pierde la cantidad usada. El vuelo sigue después del retiro.',
      'La curva demo reutiliza el sorteo criptográfico crash de PlayLiva: margen matemático del 3% y límite de 100×. No implica certificación ni promesa de ganancias. La animación y el audio no cambian el sorteo.',
      'Recargar reconecta con la ronda del servidor, sin nueva jugada ni pago duplicado. El retiro manual necesita conexión; el automático conserva el límite confirmado. Los créditos siguen siendo locales a este navegador y se comparten con otros Originals. El saldo se puede restablecer fuera de la ronda.',
    ],
  },
}
export const aviaCopy = (locale: Locale) => copy[locale]
