import { contentLocale } from '@/lib/locale'
import type { Locale } from '@/lib/types'

const copy = {
  en: {
    name: 'Liva Turbo Crash', title: 'Liva Turbo Crash — Free car crash multiplier game',
    description: 'Start the turbo, watch the multiplier rise and cash out before the car breaks down. A free PlayLiva Original with virtual credits and a 25× finish line.',
    category: 'Crash', racing: 'Crash · multiplier', start: 'START TURBO', again: 'PLAY AGAIN', cashOut: 'CASH OUT',
    ready: 'READY ON THE GRID', launch: 'TURBO IGNITION', running: 'THE MULTIPLIER IS RISING', crashed: 'TURBO OVERLOAD', finished: '25× FINISH LINE',
    secured: 'RETURN SECURED', result: 'ROUND COMPLETE', stake: 'Credits per round', auto: 'Auto cashout', off: 'Off',
    return: 'Virtual return', received: 'Credits received', lost: 'Credits used', recent: 'Recent rounds', cap: '25× maximum',
    intro: 'One car. One multiplier. Cash out before the overload.', actionHint: 'Free play with virtual credits. No deposits, cash value or prizes.',
    loading: 'Preparing the turbo…', unavailable: 'Canvas is unavailable. Try an updated browser.',
    error: 'The round could not start. Check your credits or reload and try again.',
    rulesTitle: 'How to play Liva Turbo Crash', creditsTitle: 'Virtual credits, never real money',
    credits: 'Liva Credits exist only for this demo. PlayLiva does not accept bets or deposits, and these credits cannot be withdrawn or exchanged for money or prizes. Your shared balance is stored in this browser. Older Rio Drift skill records remain separate and are not converted into credits.',
    paragraphs: [
      'Liva Turbo Crash is a free car-themed crash game from PlayLiva Originals. Choose your virtual stake, start the turbo and follow the rising multiplier. Cash out before the overload to secure a virtual return. The original blue coupe and illuminated road provide the setting; steering and driving skill do not change the outcome.',
      'Each round draws a fresh random crash point before ignition. It is independent of earlier rounds and stays hidden until the result. The multiplier starts at 1.00× after the short launch and rises smoothly. A crash can happen immediately, so waiting for a larger multiplier also means risking the credits used for that round.',
      'There is a single cashout decision, with an optional target chosen before the start. Cashing out secures stake × multiplier, rounded down to a hundredth of a credit. The car continues after your cashout so you can see where the round ends. Recent results describe completed rounds; they cannot predict the next result.',
      'At 25×, a round that has not crashed finishes and automatically secures the remaining virtual return. A crash exactly at 25× still loses, as does any cashout exactly at its crash deadline. Settings and hidden tabs do not pause the clock. Leaving or reloading abandons the unfinished round without refunding its stake; already credited returns remain in the saved balance.',
    ],
    rules: [
      'Choose 1, 5, 10, 25 or 50 virtual credits and press Start turbo. There are no steering controls.',
      'After ignition, the multiplier rises from 1.00×. Press Cash out while the round is running to secure your virtual return.',
      'Optionally choose an auto cashout before starting. It succeeds only if its target occurs strictly before the crash point.',
      'Crash points are random and independent of earlier rounds. A round can crash at 1.00×. Previous results do not predict future outcomes.',
      'The maximum is 25×. The game banks at that limit only if the crash point is beyond 25×; a crash at exactly 25× wins the timing tie.',
      'Returns equal stake × secured multiplier and round down to 0.01 credit. Each round debits and settles once.',
      'The clock continues in Settings or a hidden tab. Closing or reloading the page abandons an active round without a refund.',
      'The crash or finish reaction completes before another round or any eligible sponsor offer. Music and sound effects remain optional in Settings.',
    ],
    arcadeTitle: 'Free Originals — quick browser games', arcadeDescription: 'Discover free PlayLiva Originals and Liva Turbo Crash, the car-themed multiplier game that replaces the former Rio Drift skill challenge.',
    arcadeIntro: 'Looking for Rio Drift? Its stable game page now hosts Liva Turbo Crash, a simpler car-themed multiplier game. Your old local skill record is kept separate; it is not converted into virtual credits.',
    arcadeDetails: 'Start a round, follow the multiplier and cash out before the overload. The car drives itself and steering does not affect the random result. Explore the Originals collection for other free browser games; all virtual credits have no cash value.',
  },
  'pt-BR': {
    name: 'Liva Turbo Crash', title: 'Liva Turbo Crash — Jogo crash de carro grátis',
    description: 'Ligue o turbo, acompanhe o multiplicador e retire antes da pane. Um PlayLiva Original grátis com créditos virtuais e chegada em 25×.',
    category: 'Crash', racing: 'Crash · multiplicador', start: 'LIGAR TURBO', again: 'JOGAR DE NOVO', cashOut: 'RETIRAR',
    ready: 'PRONTO NA LARGADA', launch: 'LIGANDO O TURBO', running: 'O MULTIPLICADOR ESTÁ SUBINDO', crashed: 'PANE NO TURBO', finished: 'CHEGADA EM 25×',
    secured: 'RETORNO GARANTIDO', result: 'RODADA CONCLUÍDA', stake: 'Créditos por rodada', auto: 'Retirada automática', off: 'Desligada',
    return: 'Retorno virtual', received: 'Créditos recebidos', lost: 'Créditos usados', recent: 'Rodadas recentes', cap: 'Máximo de 25×',
    intro: 'Um carro. Um multiplicador. Retire antes da pane.', actionHint: 'Jogue grátis com créditos virtuais. Sem depósitos, valor monetário ou prêmios.',
    loading: 'Preparando o turbo…', unavailable: 'O Canvas está indisponível. Tente um navegador atualizado.',
    error: 'Não foi possível iniciar a rodada. Confira seus créditos ou recarregue e tente de novo.',
    rulesTitle: 'Como jogar Liva Turbo Crash', creditsTitle: 'Créditos virtuais, nunca dinheiro real',
    credits: 'Os Liva Credits existem apenas nesta demonstração. O PlayLiva não aceita apostas nem depósitos, e os créditos não podem ser sacados ou trocados por dinheiro ou prêmios. O saldo compartilhado fica neste navegador. Os antigos recordes de habilidade do Rio Drift continuam separados e não viram créditos.',
    paragraphs: [
      'Liva Turbo Crash é um jogo crash grátis com tema de carro da coleção PlayLiva Originals. Escolha seus créditos virtuais, ligue o turbo e acompanhe o multiplicador. Retire antes da pane para garantir o retorno virtual. O cupê azul original e a pista iluminada dão o clima; direção e habilidade ao volante não alteram o resultado.',
      'Cada rodada sorteia um novo ponto de pane antes da largada. Ele é independente das rodadas anteriores e fica oculto até o resultado. O multiplicador começa em 1,00× depois de uma breve partida e sobe de forma contínua. A pane pode ser imediata: esperar um multiplicador maior também significa arriscar os créditos usados naquela rodada.',
      'Você decide quando retirar, com a opção de configurar uma retirada automática antes de começar. O retorno é créditos da rodada × multiplicador, arredondado para baixo até o centésimo de crédito. O carro continua depois da retirada para mostrar onde a rodada termina. Os resultados recentes registram o passado e não preveem a próxima rodada.',
      'Ao chegar a 25× sem pane, a rodada termina e o retorno virtual restante é garantido automaticamente. Uma pane exatamente em 25× ainda perde, assim como uma retirada no instante exato da pane. Configurações e abas ocultas não pausam o relógio. Sair ou recarregar abandona a rodada em andamento sem devolver os créditos usados; um retorno já creditado permanece no saldo salvo.',
    ],
    rules: [
      'Escolha 1, 5, 10, 25 ou 50 créditos virtuais e toque em Ligar turbo. Não há controles de direção.',
      'Após a partida, o multiplicador sobe de 1,00×. Toque em Retirar durante a rodada para garantir seu retorno virtual.',
      'Se quiser, escolha a retirada automática antes de começar. Ela só funciona se o alvo ocorrer estritamente antes do ponto de pane.',
      'Os pontos de pane são aleatórios e independentes. Uma rodada pode terminar em 1,00×. O histórico não prevê novos resultados.',
      'O máximo é 25×. O jogo garante o retorno nesse limite apenas se o ponto de pane estiver além de 25×; uma pane exatamente em 25× tem prioridade.',
      'O retorno é créditos usados × multiplicador garantido, arredondado para baixo até 0,01 crédito. Cada rodada debita e liquida uma única vez.',
      'O relógio continua nas Configurações e em abas ocultas. Fechar ou recarregar abandona a rodada ativa sem reembolso.',
      'A reação de pane ou chegada termina antes da próxima rodada ou de qualquer oferta elegível. Música e efeitos são opcionais nas Configurações.',
    ],
    arcadeTitle: 'Originals grátis — jogos rápidos no navegador', arcadeDescription: 'Conheça os PlayLiva Originals grátis e Liva Turbo Crash, o jogo de multiplicador com carro que substitui o antigo desafio de habilidade Rio Drift.',
    arcadeIntro: 'Procurando Rio Drift? A mesma página agora traz Liva Turbo Crash, um jogo de multiplicador com carro e controles mais simples. Seu antigo recorde local continua separado e não se transforma em créditos virtuais.',
    arcadeDetails: 'Inicie uma rodada, acompanhe o multiplicador e retire antes da pane. O carro anda sozinho e a direção não interfere no resultado aleatório. Explore outros jogos grátis da coleção Originals; todos os créditos virtuais são sem valor monetário.',
  },
  'es-MX': {
    name: 'Liva Turbo Crash', title: 'Liva Turbo Crash — Juego crash de auto gratis',
    description: 'Enciende el turbo, sigue el multiplicador y retira antes de la falla. Un PlayLiva Original gratis con créditos virtuales y una meta de 25×.',
    category: 'Crash', racing: 'Crash · multiplicador', start: 'ENCENDER TURBO', again: 'JUGAR DE NUEVO', cashOut: 'RETIRAR',
    ready: 'LISTO EN LA SALIDA', launch: 'ENCENDIENDO EL TURBO', running: 'EL MULTIPLICADOR SIGUE SUBIENDO', crashed: 'FALLA DEL TURBO', finished: 'META DE 25×',
    secured: 'RETORNO ASEGURADO', result: 'RONDA COMPLETA', stake: 'Créditos por ronda', auto: 'Retiro automático', off: 'Desactivado',
    return: 'Retorno virtual', received: 'Créditos recibidos', lost: 'Créditos usados', recent: 'Rondas recientes', cap: 'Máximo de 25×',
    intro: 'Un auto. Un multiplicador. Retira antes de la falla.', actionHint: 'Juega gratis con créditos virtuales. Sin depósitos, valor monetario ni premios.',
    loading: 'Preparando el turbo…', unavailable: 'Canvas no está disponible. Prueba un navegador actualizado.',
    error: 'No se pudo iniciar la ronda. Revisa tus créditos o recarga e inténtalo de nuevo.',
    rulesTitle: 'Cómo jugar Liva Turbo Crash', creditsTitle: 'Créditos virtuales, nunca dinero real',
    credits: 'Los Liva Credits solo existen para esta demostración. PlayLiva no acepta apuestas ni depósitos, y estos créditos no se pueden retirar ni cambiar por dinero o premios. El saldo compartido se guarda en este navegador. Los antiguos récords de habilidad de Rio Drift siguen separados y no se convierten en créditos.',
    paragraphs: [
      'Liva Turbo Crash es un juego crash gratis con temática de autos de PlayLiva Originals. Elige tus créditos virtuales, enciende el turbo y sigue el multiplicador. Retira antes de la falla para asegurar un retorno virtual. El cupé azul original y la pista iluminada crean el ambiente; la dirección y la habilidad al volante no cambian el resultado.',
      'Cada ronda elige un punto de falla aleatorio antes de la salida. Es independiente de las rondas anteriores y permanece oculto hasta el resultado. El multiplicador empieza en 1.00× después de un arranque breve y sube de forma continua. La falla puede ser inmediata: esperar un multiplicador mayor también implica arriesgar los créditos de esa ronda.',
      'Tú decides cuándo retirar y puedes elegir un retiro automático antes de empezar. El retorno es créditos de la ronda × multiplicador, redondeado hacia abajo a una centésima de crédito. El auto sigue después del retiro para mostrar dónde termina la ronda. Los resultados recientes describen rondas pasadas y no predicen la siguiente.',
      'Si llega a 25× sin fallar, la ronda termina y asegura automáticamente el retorno virtual pendiente. Una falla exactamente en 25× pierde, igual que un retiro en el instante exacto de la falla. Los Ajustes y las pestañas ocultas no pausan el reloj. Salir o recargar abandona la ronda activa sin devolver sus créditos; un retorno ya acreditado permanece en el saldo guardado.',
    ],
    rules: [
      'Elige 1, 5, 10, 25 o 50 créditos virtuales y pulsa Encender turbo. No hay controles de dirección.',
      'Después del arranque, el multiplicador sube desde 1.00×. Pulsa Retirar durante la ronda para asegurar tu retorno virtual.',
      'Puedes elegir un retiro automático antes de empezar. Solo funciona si el objetivo ocurre estrictamente antes del punto de falla.',
      'Los puntos de falla son aleatorios e independientes. Una ronda puede fallar en 1.00×. El historial no predice nuevos resultados.',
      'El máximo es 25×. El juego asegura el retorno en ese límite solo si el punto de falla está después de 25×; una falla exactamente en 25× tiene prioridad.',
      'El retorno es créditos usados × multiplicador asegurado, redondeado hacia abajo a 0.01 crédito. Cada ronda descuenta y liquida una sola vez.',
      'El reloj continúa en Ajustes y pestañas ocultas. Cerrar o recargar abandona la ronda activa sin reembolso.',
      'La reacción de falla o llegada termina antes de otra ronda o una oferta elegible. Música y efectos son opcionales en Ajustes.',
    ],
    arcadeTitle: 'Originals gratis — juegos rápidos en el navegador', arcadeDescription: 'Descubre los PlayLiva Originals gratis y Liva Turbo Crash, el juego de multiplicador con auto que sustituye el antiguo reto de habilidad Rio Drift.',
    arcadeIntro: '¿Buscas Rio Drift? La misma página ahora presenta Liva Turbo Crash, un juego de multiplicador con auto y controles más simples. Tu antiguo récord local sigue separado y no se convierte en créditos virtuales.',
    arcadeDetails: 'Inicia una ronda, sigue el multiplicador y retira antes de la falla. El auto avanza solo y la dirección no cambia el resultado aleatorio. Explora otros juegos gratis de Originals; todos los créditos virtuales carecen de valor monetario.',
  },
}
export const driftCopy = (locale: Locale) => copy[contentLocale(locale)]
