import { contentLocale } from '@/lib/locale'
import type { Locale } from '@/lib/types'

const copy = {
  'pt-BR': {
    title: 'Rio Drift — Jogo de drift grátis na costa do Rio',
    description: 'Dirija um cupê original pelas curvas de uma costa inspirada no Rio. Controle o drift, mantenha o combo e bata seu recorde neste arcade grátis do PlayLiva.',
    category: 'Arcade', racing: 'Corrida · habilidade', start: 'Iniciar corrida', again: 'Tentar novamente',
    left: 'Virar à esquerda', right: 'Virar à direita', steer: 'Segure ← → ou A / D. No celular, arraste a pista ou segure uma seta.',
    score: 'Pontos', best: 'Seu recorde', combo: 'Combo', bestCombo: 'Melhor combo', distance: 'Distância', clean: 'Curvas limpas', near: 'Quase colisões',
    ready: 'A COSTA É SUA', running: 'SEGURE A LINHA', drift: 'DRIFT CONTROLADO', impact: 'FIM DA CORRIDA', result: 'MAIS UMA VOLTA?',
    coast: 'Orla', city: 'Cidade', tunnel: 'Túnel', speed: 'Velocidade', paused: 'Corrida pausada', resume: 'Continuar corrida',
    intro: 'Um cupê. A costa do Rio. Seu melhor drift.', actionHint: 'Corridas grátis. Pontos por habilidade, sem apostas nem prêmios.',
    bestNotice: 'NOVO RECORDE', storage: 'O recorde está disponível nesta sessão, mas não pôde ser salvo no navegador.',
    loading: 'Preparando a pista…', unavailable: 'Este navegador não disponibiliza Canvas 2D. Tente um navegador atualizado.',
    rulesTitle: 'Como jogar Rio Drift', creditsTitle: 'Arcade gratuito, sem apostas',
    credits: 'Cada corrida é grátis: nenhum Liva Credit é gasto ou recebido. Pontos e combos são apenas resultados do jogo, sem valor monetário, prêmios, depósitos ou saques. O saldo compartilhado dos outros Originals não muda. Redefinir Saldo restaura só esse saldo; seu recorde de drift continua separado.',
    paragraphs: [
      'Rio Drift é um jogo de carro online de habilidade, feito para pequenas sessões no celular ou no computador. Um cupê elétrico-azul original acelera sozinho por uma orla imaginária. O céu de pôr do sol dá lugar às luzes da cidade; túneis e curvas costeiras fazem parte da mesma corrida sem fim. O cenário é inspirado no Rio, sem reproduzir um mapa real.',
      'Você controla a direção. Toque e segure as setas, arraste a pista para a esquerda ou direita, ou use as teclas de direção e A/D. Antecipe a curva: segurar a direção para o lado certo permite que a traseira deslize enquanto o carro permanece dentro da pista. Solte gradualmente para recuperar a tração. O jogo não exige acelerador, freio ou botão de drift.',
      'O combo cresce com o tempo de drift controlado, até 5×. Curvas concluídas sem perder a linha e passagens perto dos veículos de serviço adicionam pontos. Esse multiplicador afeta apenas a pontuação; não é uma aposta ou retorno em créditos. As curvas e os obstáculos seguem uma sequência determinística, para que aprender a pista faça diferença.',
      'Uma colisão com a proteção ou um obstáculo encerra a corrida. Veja pontos, melhor combo e distância e tente novamente. O recorde fica neste navegador, sem ranking global ou conta. Abrir as Configurações ou ocultar a aba pausa a direção; voltar exige continuar a corrida. Recarregar abandona a corrida inacabada sem registrar pontuação e sem alterar qualquer saldo.',
    ],
    rules: [
      'Segure as setas na tela, arraste horizontalmente a pista, ou use ←/→ e A/D. Comandos opostos se anulam. A aceleração é automática.',
      'Vire para o lado da curva mantendo o carro longe das bordas. Um deslizamento controlado acumula combo a cada 1,4 segundo, até 5×; sair da linha ou virar contra a curva quebra o combo.',
      'Distância vale 1,4 ponto por metro. Drift soma pontos por tempo e ângulo, multiplicados pelo combo. Uma curva limpa soma 150 × combo; uma passagem próxima sem colisão soma 125 × combo.',
      'A velocidade sobe gradualmente. Há sempre espaço para passar os veículos de serviço. A proteção lateral e os obstáculos encerram a corrida quando atingidos.',
      'A reação de colisão termina antes da tela de resultado e de qualquer oferta. A próxima corrida só começa quando você escolhe Iniciar corrida ou Tentar novamente.',
      'Música, efeitos e vibração são opcionais nas Configurações. Ocultar a aba ou abrir o menu pausa o jogo. Continuar limpa comandos presos; recarregar abandona a tentativa atual.',
      'Recordes são locais ao navegador e podem desaparecer se seus dados forem apagados. Nenhum ponto vira crédito, dinheiro ou prêmio. Não há apostas, sorteio de resultado ou ranking global.',
    ],
    arcadeTitle: 'Jogos arcade grátis — habilidade no navegador', arcadeDescription: 'Explore o lado arcade do PlayLiva: Rio Drift, um jogo de corrida grátis com direção simples, drift controlado e recordes locais. Sem apostas ou prêmios.',
    arcadeIntro: 'Aqui, seu controle faz a diferença. Rio Drift inaugura a seleção arcade com uma corrida de habilidade: antecipe curvas, ajuste a direção e tente superar seu próprio recorde. As corridas são gratuitas e a pontuação não representa dinheiro ou créditos.',
    arcadeDetails: 'O cupê acelera sozinho, deixando você concentrado na linha da pista. No celular, arraste ou segure as setas; no computador, use ←/→ ou A/D. A sequência de curvas é determinística, a velocidade aumenta aos poucos e uma colisão encerra a tentativa. Compare o que você aprendeu entre corridas, sem um ranking global inventado.',
  },
  en: {
    title: 'Rio Drift — Free coastal arcade driving game',
    description: 'Drive an original coupe along a Rio-inspired coastline. Control your drift, build a combo and beat your local best in this free PlayLiva arcade game.',
    category: 'Arcade', racing: 'Racing · skill', start: 'Start run', again: 'Try again',
    left: 'Steer left', right: 'Steer right', steer: 'Hold ← → or A / D. On mobile, drag the road or hold an arrow.',
    score: 'Score', best: 'Your best', combo: 'Combo', bestCombo: 'Best combo', distance: 'Distance', clean: 'Clean corners', near: 'Near misses',
    ready: 'THE COAST IS YOURS', running: 'HOLD YOUR LINE', drift: 'CONTROLLED DRIFT', impact: 'RUN ENDED', result: 'ONE MORE RUN?',
    coast: 'Coast', city: 'City', tunnel: 'Tunnel', speed: 'Speed', paused: 'Run paused', resume: 'Resume run',
    intro: 'One coupe. The Rio coast. Your best drift.', actionHint: 'Free runs. Skill-based scores, no wagers or prizes.',
    bestNotice: 'NEW PERSONAL BEST', storage: 'Your best is available this session, but could not be saved in this browser.',
    loading: 'Preparing the road…', unavailable: 'This browser does not provide Canvas 2D. Try an updated browser.',
    rulesTitle: 'How to play Rio Drift', creditsTitle: 'Free arcade play, no wagering',
    credits: 'Every run is free: no Liva Credits are spent or awarded. Scores and combos are game results only, without monetary value, prizes, deposits or withdrawals. The shared balance for other Originals stays unchanged. Reset Balance restores that balance only; your drift record is separate.',
    paragraphs: [
      'Rio Drift is a skill-based online driving game designed for short mobile or desktop sessions. An original electric-blue coupe accelerates automatically along an imaginary coastline. Sunset fades into city lights; tunnels and coastal bends share the same endless run. The setting is inspired by Rio without copying a real street map.',
      'You control the steering. Hold the on-screen arrows, drag the road left or right, or use the arrow keys and A/D. Anticipate a corner: steering into the bend lets the rear slide while the car stays on the road. Ease off to recover traction. There is no accelerator, brake or separate drift button to juggle.',
      'Controlled drift time builds a combo up to 5×. Clean corners and close passes by service vehicles add score. This multiplier applies only to points, never a wager or credit return. Corners and obstacles follow a deterministic sequence, so learning the road makes a difference.',
      'Hitting the barrier or an obstacle ends your run. Review your score, best combo and distance, then try again. Your personal best stays in this browser; there is no global leaderboard or account. Opening Settings or hiding the tab pauses driving; returning requires Resume. Reloading abandons an unfinished run without recording its score or changing any balance.',
    ],
    rules: [
      'Hold the on-screen arrows, drag the road horizontally, or use ←/→ and A/D. Opposite inputs cancel. Acceleration is automatic.',
      'Steer into the corner while staying clear of the edges. Controlled sliding builds a combo every 1.4 seconds, capped at 5×. Leaving the clean line or steering against the curve breaks it.',
      'Distance earns 1.4 points per metre. Drift points depend on time and angle, multiplied by combo. A clean corner adds 150 × combo; a near miss without contact adds 125 × combo.',
      'Speed gradually increases. Service vehicles always leave room to pass. Hitting a roadside barrier or obstacle ends the run.',
      'The collision reaction finishes before the result screen or an offer appears. A new run starts only when you select Start run or Try again.',
      'Music, effects and haptics are optional in Settings. Hiding the tab or opening the menu pauses play. Resume clears stuck controls; reload abandons the current attempt.',
      'Records belong to this browser and may disappear when its data is cleared. Points never become credits, money or prizes. There is no wagering, outcome draw or global leaderboard.',
    ],
    arcadeTitle: 'Free arcade games — browser-based skill challenges', arcadeDescription: 'Explore PlayLiva arcade games: Rio Drift combines simple steering, controlled sliding and local records in a free driving challenge, without wagers or prizes.',
    arcadeIntro: 'Your control makes the difference here. Rio Drift launches the arcade selection with a driving skill challenge: anticipate corners, adjust your steering and try to improve your personal best. Runs are free and points never represent money or credits.',
    arcadeDetails: 'The coupe accelerates by itself, leaving you focused on the racing line. Drag or hold arrows on mobile; use ←/→ or A/D on desktop. The corners follow a deterministic sequence, speed rises gradually and contact ends the attempt. Compare what you learned between runs without an invented global leaderboard.',
  },
  'es-MX': {
    title: 'Rio Drift — Juego de conducción arcade gratis',
    description: 'Conduce un cupé original por una costa inspirada en Río. Controla el derrape, mantén el combo y supera tu récord local en este arcade gratis de PlayLiva.',
    category: 'Arcade', racing: 'Carreras · habilidad', start: 'Iniciar carrera', again: 'Intentar otra vez',
    left: 'Girar a la izquierda', right: 'Girar a la derecha', steer: 'Mantén ← → o A / D. En celular, arrastra la pista o mantén una flecha.',
    score: 'Puntos', best: 'Tu récord', combo: 'Combo', bestCombo: 'Mejor combo', distance: 'Distancia', clean: 'Curvas limpias', near: 'Pasadas cercanas',
    ready: 'LA COSTA ES TUYA', running: 'MANTÉN TU LÍNEA', drift: 'DERRAPE CONTROLADO', impact: 'FIN DE LA CARRERA', result: '¿UNA MÁS?',
    coast: 'Costa', city: 'Ciudad', tunnel: 'Túnel', speed: 'Velocidad', paused: 'Carrera en pausa', resume: 'Continuar carrera',
    intro: 'Un cupé. La costa de Río. Tu mejor derrape.', actionHint: 'Carreras gratis. Puntos por habilidad, sin apuestas ni premios.',
    bestNotice: 'NUEVO RÉCORD', storage: 'Tu récord está disponible esta sesión, pero no se pudo guardar en el navegador.',
    loading: 'Preparando la pista…', unavailable: 'Este navegador no ofrece Canvas 2D. Prueba un navegador actualizado.',
    rulesTitle: 'Cómo jugar Rio Drift', creditsTitle: 'Arcade gratuito, sin apuestas',
    credits: 'Cada carrera es gratis: no se gastan ni otorgan Liva Credits. Puntos y combos son solo resultados del juego, sin valor monetario, premios, depósitos ni retiros. El saldo compartido de los demás Originals no cambia. Restablecer Saldo restaura solo ese saldo; tu récord de drift es independiente.',
    paragraphs: [
      'Rio Drift es un juego de conducción online de habilidad, pensado para sesiones cortas en celular o computadora. Un cupé original azul eléctrico acelera solo por una costa imaginaria. El atardecer se convierte en luces de ciudad; túneles y curvas costeras comparten la misma carrera sin fin. El escenario se inspira en Río sin copiar un mapa real.',
      'Tú controlas la dirección. Mantén las flechas en pantalla, arrastra la pista hacia los lados o usa las flechas del teclado y A/D. Anticipa la curva: girar hacia el lado correcto permite que la parte trasera deslice sin salir de la carretera. Suelta poco a poco para recuperar tracción. No necesitas acelerador, freno ni un botón adicional de derrape.',
      'El tiempo de derrape controlado aumenta el combo hasta 5×. Las curvas limpias y las pasadas cercanas a vehículos de servicio añaden puntos. El multiplicador afecta solo la puntuación, nunca una apuesta o un retorno en créditos. Curvas y obstáculos siguen una secuencia determinística para que aprender la pista ayude.',
      'Chocar con la barrera o un obstáculo termina la carrera. Revisa puntos, mejor combo y distancia, y vuelve a intentar. El récord se guarda en este navegador, sin clasificación global ni cuenta. Abrir Ajustes u ocultar la pestaña pausa la conducción; al volver debes continuar. Recargar abandona una carrera sin terminar, sin registrar puntos ni cambiar el saldo.',
    ],
    rules: [
      'Mantén las flechas en pantalla, arrastra horizontalmente la pista o usa ←/→ y A/D. Los comandos opuestos se anulan. La aceleración es automática.',
      'Gira hacia la curva sin acercarte a los bordes. El derrape controlado aumenta el combo cada 1.4 segundos hasta 5×. Salir de la línea o girar contra la curva rompe el combo.',
      'La distancia vale 1.4 puntos por metro. El derrape suma puntos por tiempo y ángulo, multiplicados por el combo. Una curva limpia añade 150 × combo; una pasada cercana sin choque añade 125 × combo.',
      'La velocidad aumenta gradualmente. Los vehículos de servicio siempre dejan espacio para pasar. Tocar la barrera lateral o un obstáculo termina la carrera.',
      'La reacción del choque termina antes de mostrar el resultado o una oferta. La siguiente carrera solo empieza al elegir Iniciar carrera o Intentar otra vez.',
      'Música, efectos y vibración son opcionales en Ajustes. Ocultar la pestaña o abrir el menú pausa el juego. Continuar limpia comandos atascados; recargar abandona el intento actual.',
      'Los récords pertenecen a este navegador y pueden perderse al borrar sus datos. Los puntos nunca se convierten en créditos, dinero ni premios. No hay apuestas, sorteo de resultados ni clasificación global.',
    ],
    arcadeTitle: 'Juegos arcade gratis — desafíos de habilidad online', arcadeDescription: 'Descubre el arcade de PlayLiva: Rio Drift combina dirección simple, derrapes controlados y récords locales en un juego de carreras gratis, sin apuestas ni premios.',
    arcadeIntro: 'Aquí tu control hace la diferencia. Rio Drift inaugura la selección arcade con una carrera de habilidad: anticipa curvas, ajusta la dirección y supera tu propio récord. Las carreras son gratis y la puntuación no representa dinero ni créditos.',
    arcadeDetails: 'El cupé acelera solo para que puedas concentrarte en tu línea. Arrastra o mantén las flechas en celular; usa ←/→ o A/D en computadora. Las curvas siguen una secuencia determinística, la velocidad sube poco a poco y una colisión termina el intento. Compara lo aprendido entre carreras, sin inventar una clasificación global.',
  },
}
export const driftCopy = (locale: Locale) => copy[contentLocale(locale)]
