import { contentLocale } from '@/lib/locale'
import type { ContentLocale } from '@/lib/types'
import type { Locale } from '../types'
import type { ThreeGameKind } from './three-game-definitions'
const pt = {
  stake: 'Créditos por rodada', start: 'COMEÇAR', drop: 'SOLTAR BOLA', spin: 'GIRAR', rows: 'Fileiras', risk: 'Risco', low: 'Baixo', medium: 'Médio', high: 'Alto',
  ready: 'O PALCO É SEU', dropping: 'SIGA O RITMO', landed: 'NA BATIDA!', preparing: 'PREPARE A PEGADA', lifting: 'FORÇA TOTAL', failed: 'A BARRA CAIU',
  cashout: 'RETIRAR', cashed: 'RETORNO GARANTIDO', auto: 'Retirada automática', off: 'Desligada', loading: 'Preparando seu jogo…', retry: 'Tentar novamente', loadError: 'Não foi possível carregar o jogo.',
  rules: 'Como jogar', creditsTitle: 'Diversão com créditos virtuais', credits: 'Liva Credits são virtuais e não têm valor monetário. O PlayLiva não aceita depósitos nem apostas com dinheiro real. Não há saques ou prêmios reais.',
  interruption: 'Sair ou recarregar durante uma rodada abandona a jogada. Os créditos usados não são devolvidos e o resultado não é retomado.',
  roundError: 'Não foi possível continuar a rodada. Tente novamente sem recarregar a página.',
  error: 'Não foi possível iniciar. Confira seus créditos e conclua a rodada anterior.', return: 'Retorno', history: 'Últimos resultados',
  free: 'RODADAS GRÁTIS', meter: 'MEDIDOR DE SAMBA', bonus: 'O DESFILE COMEÇOU', summary: 'UM DESFILE DE OURO', total: 'Total do bônus', continue: 'CONTINUAR', retrigger: 'RODADA EXTRA', anticipation: 'MAIS UMA MÁSCARA?',
  spinning: 'NO RITMO DO SAMBA', result: 'RESULTADO', win: 'BOA BATIDA', big: 'ESPETÁCULO!', huge: 'OURO DO CARNAVAL!', payNote: '20 linhas fixas. Cada valor é o retorno por linha, em múltiplos de 1/20 dos créditos usados. Somente a maior sequência por linha paga.',
  symbols: ['Coroa Curinga','Máscara de Bônus','Nota de Samba','Tambores','Leque','Joia','Arara','Pandeiro','Coração','Diamante','Trevo','Espada'],
}
type Copy = { [K in keyof typeof pt]: typeof pt[K] }
const en: Copy = {
  stake:'Credits per round',start:'START LIFT',drop:'DROP BALL',spin:'SPIN',rows:'Rows',risk:'Risk',low:'Low',medium:'Medium',high:'High',ready:'THE STAGE IS YOURS',dropping:'FOLLOW THE RHYTHM',landed:'RIGHT ON BEAT!',preparing:'SET YOUR GRIP',lifting:'HEAVY STRAIN',failed:'BAR DOWN',cashout:'CASH OUT',cashed:'RETURN LOCKED',auto:'Auto cashout',off:'Off',loading:'Preparing your game…',retry:'Try again',loadError:'The game could not load.',rules:'How to play',creditsTitle:'Play with virtual credits',credits:'Liva Credits are virtual and have no monetary value. PlayLiva accepts no deposits or real-money wagers. No withdrawals or real prizes.',interruption:'Leaving or reloading during a round abandons it. Spent credits are not refunded and the outcome is not resumed.',roundError:'The round could not continue. Try again without reloading the page.',error:'Could not start. Check your credits and finish the previous round.',return:'Return',history:'Recent results',free:'FREE SPINS',meter:'SAMBA METER',bonus:'THE PARADE BEGINS',summary:'A GOLDEN PARADE',total:'Bonus total',continue:'CONTINUE',retrigger:'EXTRA SPIN',anticipation:'ONE MORE MASK?',spinning:'FEEL THE SAMBA',result:'RESULT',win:'NICE RHYTHM',big:'SHOWTIME!',huge:'CARNAVAL GOLD!',payNote:'20 fixed lines. Each value is a line return in multiples of 1/20 of the total credits played. Only the longest match on each line pays.',symbols:['Crown Wild','Mask Scatter','Samba Note','Drums','Fan','Jewel','Macaw','Tambourine','Heart','Diamond','Club','Spade'],
}
const es: Copy = {
  stake:'Créditos por ronda',start:'LEVANTAR',drop:'SOLTAR BOLA',spin:'GIRAR',rows:'Filas',risk:'Riesgo',low:'Bajo',medium:'Medio',high:'Alto',ready:'EL ESCENARIO ES TUYO',dropping:'SIGUE EL RITMO',landed:'¡AL COMPÁS!',preparing:'PREPARA EL AGARRE',lifting:'MÁXIMO ESFUERZO',failed:'CAYÓ LA BARRA',cashout:'RETIRAR',cashed:'RETORNO ASEGURADO',auto:'Retiro automático',off:'Desactivado',loading:'Preparando tu juego…',retry:'Reintentar',loadError:'No se pudo cargar el juego.',rules:'Cómo jugar',creditsTitle:'Diversión con créditos virtuales',credits:'Los Liva Credits son virtuales y no tienen valor monetario. PlayLiva no acepta depósitos ni apuestas con dinero real. Sin retiros ni premios reales.',interruption:'Salir o recargar durante una ronda la abandona. No se devuelven los créditos usados ni se reanuda el resultado.',roundError:'No se pudo continuar la ronda. Reintenta sin recargar la página.',error:'No se pudo iniciar. Revisa tus créditos y termina la ronda anterior.',return:'Retorno',history:'Últimos resultados',free:'GIROS GRATIS',meter:'MEDIDOR DE SAMBA',bonus:'EMPIEZA EL DESFILE',summary:'UN DESFILE DE ORO',total:'Total del bono',continue:'CONTINUAR',retrigger:'GIRO EXTRA',anticipation:'¿UNA MÁSCARA MÁS?',spinning:'SIENTE LA SAMBA',result:'RESULTADO',win:'BUEN RITMO',big:'¡ESPECTÁCULO!',huge:'¡ORO DEL CARNAVAL!',payNote:'20 líneas fijas. Cada valor es el retorno por línea en múltiplos de 1/20 de los créditos usados. Solo paga la secuencia más larga de cada línea.',symbols:['Corona Comodín','Máscara de Bono','Nota de Samba','Tambores','Abanico','Joya','Guacamaya','Pandereta','Corazón','Diamante','Trébol','Espada'],
}
export const threeCopy = (locale: Locale) => ({ en, 'pt-BR': pt, 'es-MX': es })[contentLocale(locale)]
const descriptions: Record<ContentLocale, Record<ThreeGameKind, string>> = {
 'pt-BR': { 'samba-drop':'Plinko grátis no ritmo do Brasil. Escolha fileiras e risco, acompanhe cada quique e descubra seu multiplicador neste jogo instantâneo PlayLiva Original.', 'skuptu-levanta':'Jogo crash grátis de academia com Skuptu. Acompanhe o levantamento de peso e retire antes da barra cair. PlayLiva Original com créditos virtuais.', 'carnaval-gold':'Um caça-níquel de carnaval grátis com 20 linhas, máscaras, rodadas grátis e Medidor de Samba até ×5. Um slot PlayLiva Original.' },
 en: { 'samba-drop':'Free Plinko with a Brazilian rhythm. Choose rows and risk, follow every bounce and discover your multiplier in this PlayLiva Original instant game.', 'skuptu-levanta':'A free crash game of strength and tension. Follow the heavy deadlift and cash out before the bar falls. Virtual credits only.', 'carnaval-gold':'A free carnival slot with 20 lines, Scatter masks, free spins and a Samba Meter up to ×5. An original PlayLiva celebration.' },
 'es-MX': { 'samba-drop':'Plinko gratis al ritmo de Brasil. Elige filas y riesgo, sigue cada rebote y descubre tu multiplicador en este juego instantáneo PlayLiva Original.', 'skuptu-levanta':'Un juego crash gratis de fuerza y tensión. Sigue el levantamiento y retira antes de que caiga la barra. Solo créditos virtuales.', 'carnaval-gold':'Un slot de carnaval gratis con 20 líneas, máscaras, giros gratis y Medidor de Samba hasta ×5. Una celebración PlayLiva Original.' },
}
const rules: Record<ContentLocale, Record<ThreeGameKind, string[]>> = {
 'pt-BR': {
 'samba-drop':['Escolha de 1 a 50 créditos, 8, 12 ou 16 fileiras e risco baixo, médio ou alto antes de soltar a bola.','Cada contato escolhe esquerda ou direita com a mesma probabilidade. O caminho completo é sorteado antes do lançamento e a bola termina no compartimento correspondente.','Os multiplicadores mudam com as fileiras e o risco. Os compartimentos externos são mais raros; risco alto concentra o retorno nesses resultados.','Retorno = créditos usados × multiplicador, arredondado para baixo a 0,01 crédito. O valor é creditado uma única vez na chegada.','Retorno teórico próximo de 97% antes do arredondamento dos créditos; isso não garante retorno em uma sessão.'],
 'skuptu-levanta':['Escolha de 1 a 50 créditos e inicie o levantamento. O multiplicador sobe enquanto Skuptu mantém a barra.','Retire durante o levantamento e antes da falha. Retirada e falha no mesmo instante resultam em perda.','A retirada automática usa o limite escolhido antes da rodada. O levantamento continua até a falha mesmo depois de uma retirada bem-sucedida.','Retorno = créditos usados × multiplicador na retirada, arredondado para baixo a 0,01 crédito. Uma única liquidação por rodada.','Curva demo com margem de 3% e limite de 100×. A falha é sorteada antes da animação; a duração não revela um resultado futuro.'],
 'carnaval-gold':['Cinco rolos, três posições e 20 linhas fixas. Três, quatro ou cinco símbolos iguais da esquerda para a direita pagam conforme a tabela.','A Coroa Curinga aparece nos rolos 2 a 5 e substitui símbolos pagantes. Não substitui Máscaras ou Notas.','3, 4 ou 5+ Máscaras em qualquer posição no giro pago concedem 8, 12 ou 20 rodadas grátis.','No bônus, cada Nota aumenta o Medidor de Samba em +1 antes do pagamento do giro, de ×1 até ×5. O nível permanece até o fim do bônus.','Cada Máscara no bônus adiciona uma rodada, até 32 rodadas grátis no total. Retorno limitado a 500× por giro; cada giro arredonda para baixo a 0,01 crédito.','Normal e Turbo alteram somente o tempo de apresentação. Um giro pago e suas rodadas grátis formam um ciclo completo.'],
 },
 en: {
 'samba-drop':['Choose 1–50 credits, 8, 12 or 16 rows and low, medium or high risk before dropping.','Each peg chooses left or right with equal probability. The full path is drawn before release and the ball lands in its matching bucket.','Multipliers change with rows and risk. Outer buckets are rarer; high risk concentrates return in those outcomes.','Return = credits played × bucket multiplier, rounded down to 0.01 credit. It is credited once on landing.','Theoretical return is close to 97% before credit rounding; this does not guarantee a session return.'],
 'skuptu-levanta':['Choose 1–50 credits and start the lift. The multiplier rises while Skuptu controls the bar.','Cash out during the lift and strictly before failure. A cashout at the failure deadline loses.','Auto cashout uses the target selected before the round. The lift continues to failure after a successful cashout.','Return = credits played × cashout multiplier, rounded down to 0.01 credit. Each wager settles only once.','The demo curve has a 3% edge and a 100× cap. Failure is drawn before animation; duration does not reveal a future outcome.'],
 'carnaval-gold':['Five reels, three positions and 20 fixed lines. Three, four or five matching symbols from left to right pay the table rates.','Crown Wild appears on reels 2–5 and substitutes for paying symbols, never Masks or Notes.','3, 4 or 5+ Masks anywhere on a paid spin award 8, 12 or 20 free spins.','In the bonus, each Note raises Samba Meter by +1 before that spin pays, from ×1 up to ×5. The level persists for the bonus.','Each bonus Mask adds one spin, capped at 32 free spins in total. Returns are capped at 500× per spin; each spin rounds down to 0.01 credit.','Normal and Turbo change presentation timing only. A paid spin and all its free spins form one complete cycle.'],
 },
 'es-MX': {
 'samba-drop':['Elige de 1 a 50 créditos, 8, 12 o 16 filas y riesgo bajo, medio o alto antes de soltar.','Cada contacto elige izquierda o derecha con igual probabilidad. La ruta se sortea antes del lanzamiento y termina en su casilla correspondiente.','Los multiplicadores cambian con las filas y el riesgo. Las casillas externas son más raras; el riesgo alto concentra ahí el retorno.','Retorno = créditos usados × multiplicador, redondeado hacia abajo a 0.01 crédito. Se abona una sola vez al llegar.','Retorno teórico cercano al 97% antes del redondeo; no garantiza un retorno por sesión.'],
 'skuptu-levanta':['Elige de 1 a 50 créditos e inicia el levantamiento. El multiplicador sube mientras Skuptu controla la barra.','Retira durante el levantamiento y antes del fallo. Un retiro en el instante del fallo pierde.','El retiro automático usa el límite elegido antes de la ronda. El levantamiento sigue hasta el fallo después de un retiro exitoso.','Retorno = créditos usados × multiplicador de retiro, redondeado hacia abajo a 0.01 crédito. Cada jugada se liquida una sola vez.','Curva demo con margen del 3% y límite de 100×. El fallo se sortea antes de la animación; la duración no revela un resultado futuro.'],
 'carnaval-gold':['Cinco rodillos, tres posiciones y 20 líneas fijas. Tres, cuatro o cinco símbolos iguales de izquierda a derecha pagan según la tabla.','Corona Comodín aparece en los rodillos 2–5 y sustituye símbolos de pago, nunca Máscaras ni Notas.','3, 4 o 5+ Máscaras en cualquier posición de un giro pagado otorgan 8, 12 o 20 giros gratis.','En el bono, cada Nota sube el Medidor de Samba +1 antes del pago, de ×1 hasta ×5. El nivel se mantiene durante el bono.','Cada Máscara del bono añade un giro, hasta 32 giros gratis en total. Retorno limitado a 500× por giro, redondeado hacia abajo a 0.01 crédito.','Normal y Turbo solo cambian la presentación. Un giro pagado y todos sus giros gratis forman un ciclo completo.'],
 },
}
export const threeDescription = (kind: ThreeGameKind, locale: Locale) => descriptions[contentLocale(locale)][kind]
export const threeRules = (kind: ThreeGameKind, locale: Locale) => rules[contentLocale(locale)][kind]

export const threeNumber = (value: number, locale: Locale, digits: number) => new Intl.NumberFormat(locale, { minimumFractionDigits: digits, maximumFractionDigits: digits, useGrouping: false }).format(value)
