import { contentLocale } from '@/lib/locale'
import type { ContentLocale } from '@/lib/types'
import type {Locale} from '@/lib/types'
// Targeted gaps only. Sources checked 2026-09-27; no odds, popularity or availability claims.
type Supplement={whatIsIt:string;howItWorks:string[];description?:string;shortDescription?:string;mechanics?:string[]}
export const ENTITY_SOURCES:Record<string,string>={spaceman:'https://www.pragmaticplay.com/en/games/spaceman/','gates-of-olympus':'https://www.pragmaticplay.com/en/games/gates-of-olympus/','sweet-bonanza':'https://www.pragmaticplay.com/en/games/sweet-bonanza-slot/','crazy-time':'https://games.evolution.com/live-casino/game-shows/crazy-time/',plinko:'https://spribe.co/games/plinko'}
const copy:Partial<Record<ContentLocale,Record<string,Supplement>>>={
 en:{
 g3:{whatIsIt:'Spaceman is a Pragmatic Play crash game built around a rising multiplier and an astronaut flight. It supports a partial cash-out, which separates part of a position from the amount left in the round.',howItWorks:['The multiplier rises while the flight continues; cashing out applies the current multiplier.','A partial cash-out closes half of the position. The remaining part stays exposed until it is cashed out or the flight ends.']},
 g5:{whatIsIt:'Gates of Olympus is a Pragmatic Play slot with a mythology theme and pay-anywhere symbols. It combines tumbling wins with multiplier symbols; it does not require matching symbols to connect.',howItWorks:['Matching symbols can form wins anywhere on the grid, then disappear in a tumble.','Scatter symbols activate free spins. Qualifying multipliers contribute to a running bonus multiplier.'],description:'A mythology-themed slot with pay-anywhere symbols, tumbles and a running bonus multiplier.',shortDescription:'Pay-anywhere tumbles and an accumulating bonus multiplier.'},
 g6:{whatIsIt:'Sweet Bonanza is a Pragmatic Play slot with fruit and candy symbols. Matching symbols count anywhere on the grid, rather than needing to connect into a cluster.',howItWorks:['Matching-symbol counts determine wins; winning symbols disappear and new symbols tumble into their places.','Scatters activate free spins, where multiplier symbols can modify the result of a tumbling sequence.'],description:'A fruit-and-candy slot with pay-anywhere wins, tumbles and free-spin multipliers.',shortDescription:'Candy-themed pay-anywhere wins with tumbling symbols.',mechanics:['Pay anywhere','Tumbles','Free spins','Bonus multipliers']},
 g8:{whatIsIt:'Crazy Time is an Evolution live game show built around a hosted wheel. Number sections and four separate bonus games give it a different structure from a live roulette table.',howItWorks:['Players select number or bonus positions before the main wheel stops.','A matching bonus position leads into Coin Flip, Cash Hunt, Pachinko or Crazy Time; Top Slot can assign multipliers to selected positions.']},
 g10:{whatIsIt:'Plinko by SPRIBE is an instant game in which a ball passes through rows of pegs toward a multiplier at the bottom. Risk and row settings belong to this game’s configuration, not to every game using the Plinko name.',howItWorks:['Choose the available risk and row settings before releasing the ball.','The ball descends through the board and finishes in a multiplier position. Its animation does not make the outcome predictable.']},
 },
 'es-MX':{
 g6:{whatIsIt:'Sweet Bonanza es un slot de Pragmatic Play con frutas y dulces. Cuenta símbolos iguales en cualquier posición de la cuadrícula, sin exigir que formen un grupo conectado.',howItWorks:['Las combinaciones ganadoras desaparecen y nuevos símbolos caen en cascada.','Los símbolos dispersos activan giros gratis; los multiplicadores pueden modificar el resultado de la secuencia de cascadas.'],description:'Slot de frutas y dulces con pagos en cualquier posición, cascadas y multiplicadores en giros gratis.',shortDescription:'Dulces, cascadas y pagos en cualquier posición.',mechanics:['Pago en cualquier posición','Cascadas','Giros gratis','Multiplicadores del bono']},
 g10:{whatIsIt:'Plinko de SPRIBE es un juego instantáneo en el que una pelota atraviesa filas de clavijas hasta una posición multiplicadora. La configuración de filas y riesgo pertenece a esta edición, no a todos los juegos llamados Plinko.',howItWorks:['Elige las opciones de riesgo y filas disponibles antes de soltar la pelota.','La pelota baja por el tablero hasta un multiplicador. La animación no permite predecir el resultado.']},
 },
 'pt-BR':{
 g10:{whatIsIt:'Plinko da SPRIBE é um jogo instantâneo em que uma bolinha atravessa fileiras de pinos até uma posição multiplicadora. As opções de risco e fileiras pertencem a esta edição, não a todo jogo que usa o nome Plinko.',howItWorks:['Escolha entre as opções disponíveis de risco e fileiras antes de soltar a bolinha.','A bolinha desce pelo tabuleiro até um multiplicador. A animação não permite prever o resultado.']},
 },
}
export const entitySupplement=(id:string,locale:Locale)=>copy[contentLocale(locale)]?.[id]
