import { contentLocale } from '@/lib/locale'
import type { ContentLocale } from '@/lib/types'
import type { Locale } from '@/lib/types'

const en = {
  description: 'Play Liva Blackjack free: six decks, blackjack pays 3:2, Hit, Stand, Double and Split. Virtual Liva Credits only. No deposits or monetary value.',
  discovery: 'Your table. Your decision. Classic blackjack with a six-deck shoe, crisp cards and room to split your hand.',
  posterAlt: 'Original ivory Ace and King cards above an emerald PlayLiva blackjack table with gold chips.',
  category: 'Table Games', categoryTitle: 'A seat at our own table.',
  categoryDescription: 'Play Liva Blackjack with virtual credits. A separate PlayLiva Original, not a provider or operator game.',
  loading: 'Preparing your table…', ready: 'Your next hand awaits', dealing: 'Dealing…', playerTurn: 'Your decision', dealerTurn: 'Dealer plays', settling: 'Checking the hands…',
  deal: 'Deal', again: 'Next hand', hit: 'Hit', stand: 'Stand', double: 'Double', split: 'Split',
  bet: 'Bet', dealer: 'Dealer', player: 'Your hand', hand: 'Hand', active: 'Your turn', stood: 'Standing', doubled: 'Doubled', splitAces: 'Split Aces',
  blackjack: 'BLACKJACK', win: 'WIN', loss: 'DEALER WINS', push: 'PUSH', bust: 'BUST',
  returned: 'RETURN', totalReturn: 'TOTAL RETURN', totalBet: 'Total bet', soft: 'Soft', hidden: 'Face-down card',
  spades: 'spades', hearts: 'hearts', diamonds: 'diamonds', clubs: 'clubs', ace: 'Ace', jack: 'Jack', queen: 'Queen', king: 'King',
  shortRules: 'BLACKJACK PAYS 3:2', dealerRule: 'Dealer stands on soft 17',
  insufficient: 'Not enough Liva Credits. Choose a smaller bet or reset your demo balance.',
  unavailable: 'This hand cannot continue. Credits already used stay spent. Start a new hand or reload.',
  retry: 'Return to table', how: 'Rules & payouts',
  rules: 'Six decks. Get closer to 21 than the dealer without going over. Aces count as 1 or 11. The dealer draws below 17 and stands on all 17s, including soft 17. The dealer checks for blackjack before your decisions. Both naturals push.',
  actionRules: 'Hit or Stand. Double on any initial two-card hand, including after a split: add the same bet, receive one card and stand. You may split two equal-value cards (10/J/Q/K count as the same value), up to three hands. Each split adds one equal bet. Play each hand in order; the dealer plays once.',
  aceRules: 'Split Aces once only. Each Ace gets one additional card; no Hit, Double or resplit. A 21 after a split is an ordinary win, not blackjack. No insurance or surrender.',
  payouts: 'RETURN includes your bet: a normal win returns 2×, a push 1×, a loss zero and an initial blackjack 2.5× (3:2 profit). For a 10.00 bet, blackjack returns 25.00; a normal win returns 20.00. Each split hand settles independently.',
  interruption: 'Reloading or leaving mid-hand ends that hand. Credits already used stay spent; unfinished hands do not resume or refund. Booked returns stay saved when local storage is available.',
  notice: 'Free-play demo · No deposits or withdrawals · Liva Credits have no monetary value. Not certified or a real-money game.',
  realBoundary: 'Play real-money blackjack at approved operators. This does not mean Liva Blackjack is available there.',
  verifiedReferral: 'External recommendation: the separately verified Blackjack Live listing. This is not the PlayLiva Original.',
}
type Copy = { [K in keyof typeof en]: string }
const COPY: Record<ContentLocale, Copy> = {
  en,
  'pt-BR': {
    description: 'Jogue Liva Blackjack grátis: seis baralhos, blackjack paga 3:2, pedir carta, parar, dobrar e dividir. Só Liva Credits virtuais. Sem depósitos ou valor monetário.',
    discovery: 'Sua mesa. Sua decisão. Blackjack clássico com seis baralhos, cartas elegantes e a opção de dividir sua mão.',
    posterAlt: 'Cartas originais de Ás e Rei em marfim sobre uma mesa esmeralda de blackjack PlayLiva, com fichas douradas.',
    category: 'Jogos de Mesa', categoryTitle: 'Seu lugar à nossa mesa.',
    categoryDescription: 'Jogue Liva Blackjack com créditos virtuais. Um PlayLiva Original separado, não um jogo de provedor ou operador.',
    loading: 'Preparando sua mesa…', ready: 'Sua próxima mão espera por você', dealing: 'Distribuindo…', playerTurn: 'Você decide', dealerTurn: 'Vez da mesa', settling: 'Conferindo as mãos…',
    deal: 'Distribuir', again: 'Nova mão', hit: 'Pedir carta', stand: 'Parar', double: 'Dobrar', split: 'Dividir',
    bet: 'Aposta', dealer: 'Croupier', player: 'Sua mão', hand: 'Mão', active: 'Sua vez', stood: 'Parou', doubled: 'Dobrou', splitAces: 'Ases divididos',
    blackjack: 'BLACKJACK', win: 'VITÓRIA', loss: 'A CASA VENCEU', push: 'EMPATE', bust: 'PASSOU DE 21',
    returned: 'RETORNO', totalReturn: 'RETORNO TOTAL', totalBet: 'Aposta total', soft: 'Suave', hidden: 'Carta virada para baixo',
    spades: 'espadas', hearts: 'copas', diamonds: 'ouros', clubs: 'paus', ace: 'Ás', jack: 'Valete', queen: 'Dama', king: 'Rei',
    shortRules: 'BLACKJACK PAGA 3:2', dealerRule: 'A mesa para no 17 suave',
    insufficient: 'Liva Credits insuficientes. Diminua a aposta ou redefina seu saldo demo.',
    unavailable: 'Não foi possível continuar esta mão. Os créditos usados continuam gastos. Inicie uma nova mão ou recarregue.',
    retry: 'Voltar à mesa', how: 'Regras e pagamentos',
    rules: 'Seis baralhos. Chegue mais perto de 21 do que a mesa, sem ultrapassar. Ases valem 1 ou 11. A mesa pede carta abaixo de 17 e para em qualquer 17, inclusive o suave. O blackjack da mesa é verificado antes das suas decisões. Dois blackjacks naturais empatam.',
    actionRules: 'Peça carta ou pare. Você pode dobrar qualquer mão inicial de duas cartas, inclusive após dividir: adicione a mesma aposta, receba uma carta e pare. Divida cartas de mesmo valor (10/J/Q/K valem o mesmo), até três mãos. Cada divisão exige uma aposta igual. Jogue uma mão por vez; a mesa joga uma única vez.',
    aceRules: 'Ases só podem ser divididos uma vez. Cada Ás recebe uma carta adicional, sem pedir mais cartas, dobrar ou dividir novamente. Um 21 após dividir é uma vitória comum, não blackjack. Sem seguro ou rendição.',
    payouts: 'RETORNO inclui sua aposta: vitória comum devolve 2×, empate 1×, derrota zero e blackjack inicial 2,5× (lucro de 3:2). Com aposta de 10,00, blackjack retorna 25,00; vitória comum retorna 20,00. Cada mão dividida é paga separadamente.',
    interruption: 'Recarregar ou sair durante uma mão encerra essa mão. Os créditos usados continuam gastos, sem retomada ou reembolso. Retornos já registrados ficam salvos quando o armazenamento local está disponível.',
    notice: 'Demo grátis · Sem depósitos ou saques · Liva Credits não têm valor monetário. Não é um jogo certificado nem de dinheiro real.',
    realBoundary: 'Jogue blackjack com dinheiro real em operadores aprovados. Isso não significa que Liva Blackjack esteja disponível lá.',
    verifiedReferral: 'Recomendação externa: a ficha de Blackjack Live, verificada separadamente. Não é o PlayLiva Original.',
  },
  'es-MX': {
    description: 'Juega Liva Blackjack gratis: seis barajas, blackjack paga 3:2, pedir carta, plantarse, doblar y dividir. Solo Liva Credits virtuales. Sin depósitos ni valor monetario.',
    discovery: 'Tu mesa. Tu decisión. Blackjack clásico con seis barajas, cartas elegantes y la opción de dividir tu mano.',
    posterAlt: 'Cartas originales de As y Rey en marfil sobre una mesa esmeralda de blackjack PlayLiva, con fichas doradas.',
    category: 'Juegos de Mesa', categoryTitle: 'Tu lugar en nuestra mesa.',
    categoryDescription: 'Juega Liva Blackjack con créditos virtuales. Un PlayLiva Original independiente, no un juego de proveedor u operador.',
    loading: 'Preparando tu mesa…', ready: 'Tu próxima mano te espera', dealing: 'Repartiendo…', playerTurn: 'Tú decides', dealerTurn: 'Turno del crupier', settling: 'Revisando las manos…',
    deal: 'Repartir', again: 'Nueva mano', hit: 'Pedir carta', stand: 'Plantarse', double: 'Doblar', split: 'Dividir',
    bet: 'Apuesta', dealer: 'Crupier', player: 'Tu mano', hand: 'Mano', active: 'Tu turno', stood: 'Plantado', doubled: 'Doblada', splitAces: 'Ases divididos',
    blackjack: 'BLACKJACK', win: 'VICTORIA', loss: 'GANA LA CASA', push: 'EMPATE', bust: 'TE PASASTE',
    returned: 'RETORNO', totalReturn: 'RETORNO TOTAL', totalBet: 'Apuesta total', soft: 'Suave', hidden: 'Carta boca abajo',
    spades: 'picas', hearts: 'corazones', diamonds: 'diamantes', clubs: 'tréboles', ace: 'As', jack: 'Jota', queen: 'Reina', king: 'Rey',
    shortRules: 'BLACKJACK PAGA 3:2', dealerRule: 'La casa se planta en 17 suave',
    insufficient: 'No tienes suficientes Liva Credits. Reduce la apuesta o restablece tu saldo demo.',
    unavailable: 'No se pudo continuar esta mano. Los créditos usados siguen gastados. Inicia otra mano o recarga.',
    retry: 'Volver a la mesa', how: 'Reglas y pagos',
    rules: 'Seis barajas. Acércate más a 21 que la casa sin pasarte. Los Ases valen 1 u 11. La casa pide carta por debajo de 17 y se planta en cualquier 17, incluido el suave. El blackjack de la casa se comprueba antes de tus decisiones. Dos blackjacks naturales empatan.',
    actionRules: 'Pide carta o plántate. Puedes doblar cualquier mano inicial de dos cartas, incluso después de dividir: añade la misma apuesta, recibe una carta y plántate. Divide cartas de igual valor (10/J/Q/K valen lo mismo), hasta tres manos. Cada división requiere una apuesta igual. Juega cada mano por turno; la casa juega una sola vez.',
    aceRules: 'Los Ases solo se dividen una vez. Cada As recibe una carta adicional, sin pedir más, doblar ni volver a dividir. Un 21 después de dividir es una victoria normal, no blackjack. Sin seguro ni rendición.',
    payouts: 'RETORNO incluye tu apuesta: victoria normal devuelve 2×, empate 1×, derrota cero y blackjack inicial 2.5× (ganancia de 3:2). Con apuesta de 10.00, blackjack retorna 25.00; victoria normal retorna 20.00. Cada mano dividida se paga por separado.',
    interruption: 'Recargar o salir a mitad de una mano la termina. Los créditos usados siguen gastados, sin reanudación ni reembolso. Los retornos ya registrados se guardan cuando el almacenamiento local está disponible.',
    notice: 'Demo gratis · Sin depósitos ni retiros · Liva Credits no tienen valor monetario. No es un juego certificado ni de dinero real.',
    realBoundary: 'Juega blackjack con dinero real en operadores aprobados. Esto no significa que Liva Blackjack esté disponible allí.',
    verifiedReferral: 'Recomendación externa: la ficha de Blackjack Live, verificada por separado. No es el PlayLiva Original.',
  },
}
export const blackjackCopy = (locale: Locale): Copy => COPY[contentLocale(locale)]
