'use client'
import Image from 'next/image'
import { ArrowRight,Play } from 'lucide-react'
import { useCountry } from '@/components/country-context'
import { LocaleLink } from '@/components/locale-link'
import { THREE_GAMES,gamePoster,type ThreeGameKind } from '@/lib/originals/three-game-definitions'
import { threeDescription } from '@/lib/originals/three-game-copy'
import { originalsDiscoveryCopy } from '@/lib/originals/discovery'
import styles from './originals-discovery.module.css'
export function ThreeGameFeature({kind,surface}:{kind:ThreeGameKind;surface:'home'|'hub'|'category'}){const {locale}=useCountry(),game=THREE_GAMES.find(g=>g.slug===kind)!,copy=originalsDiscoveryCopy(locale),Heading=surface==='hub'?'h2':'h3';return <article className={styles.card} data-original-card={kind} data-surface={surface}><LocaleLink href={`/play/${kind}`} prefetch={false} className={styles.posterLink} aria-label={`${copy.playFree}: ${game.title[locale]}`}><Image src={gamePoster(kind)} alt={game.title[locale]} fill sizes="(max-width:767px) 100vw,700px" className={styles.poster}/><span className={styles.playIcon}><Play size={26}/></span></LocaleLink><div className={styles.cardBody}><div className={styles.labels}><span className={styles.badge}>{copy.freePlay}</span><span>{copy.newBadge}</span></div><Heading className={styles.gameTitle}>{game.title[locale]}</Heading><p className={styles.description}>{threeDescription(kind,locale)}</p><p className={styles.credits}>{copy.virtualCredits}</p><LocaleLink href={`/play/${kind}`} prefetch={false} className={styles.playButton}><Play size={18}/>{copy.playFree}<ArrowRight size={18}/></LocaleLink><p className={styles.cardNote}>{copy.noDeposits} · {copy.noValue}</p></div></article>}
