import type { Locale } from '@/lib/types'
const en = {
  description: 'Play Liva Mines: Jungle Gold free. Reveal treasure on a 5×5 jungle board, grow your golden trail and cash out virtual Liva Credits. No deposits or withdrawals.',
  discovery: 'Every safe tile adds to your golden trail. Explore the jungle, grow your multiplier and secure your treasure before a mine ends the adventure.',
  posterAlt: 'Original emerald jungle stone board with glowing gold treasure and a winding golden trail.',
  category: 'Instant Games', categoryTitle: 'Find treasure. Make your own trail.',
  categoryDescription: 'Our original jungle Mines adventure with virtual credits. Separate from the provider games below.',
  loading: 'Preparing your jungle board…', board: 'Jungle treasure board', mines: 'Mines', count: 'Mine count', stake: 'Stake',
  ready: 'Your jungle adventure', active: 'Pick a tile', cashed_out: 'Treasure secured', mine_hit: 'You hit a mine', result: 'Round complete', error: 'Round interrupted',
  start: 'Start', again: 'Play again', cash: 'Cash out', pickFirst: 'Pick a tile first', potential: 'Potential return', returned: 'Return', profit: 'Net result',
  safe: 'Safe', mine: 'Mine', hidden: 'Unopened', tile: 'Tile', trail: 'Treasure trail', choose: 'Pick safe tiles. Secure your treasure.',
  last: 'Last result', credits: 'Liva Credits', insufficient: 'Not enough Liva Credits. Choose a smaller stake or reset your demo balance.',
  unavailable: 'This round could not continue safely. Return to ready to try again.', retry: 'Return to ready',
  how: 'How to play & payouts',
  rules: 'Choose your stake and 1, 3, 5, 7 or 10 mines. Start spends your virtual stake once. All mines are placed before you pick a tile. Safe picks reveal treasure and extend your trail. A mine ends the round with no return. Cash out after any safe pick; finding every safe tile secures the treasure automatically.',
  payouts: 'With m mines and k safe picks, survival probability is C(25−m,k) / C(25,k). The multiplier is 0.97 divided by that probability: one 3% demo edge, not 3% per pick. Multipliers are floored to six decimals, then returns to the smallest credit unit. The large multiplier label is floored to two decimals; the cashout amount uses all six. Return includes your stake. No certification or provably-fair claim.',
  interruption: 'Local demo only. Reloading or leaving during an active round keeps the debited stake spent. An unfinished round does not resume and receives no automatic refund or payout. Your next visit starts ready.',
  notice: 'Liva Credits have no monetary value. No deposits or withdrawals. Take breaks and play responsibly.',
  realBoundary: 'Explore real-money instant games at approved operators eligible for your selected market. Liva Mines is our free-play Original, not a game offered by these operators.',
}
type MinesCopy = { [K in keyof typeof en]: string }
const copy: Record<Locale, MinesCopy> = {
  en,
  'pt-BR': {
    description: 'Jogue Liva Mines: Jungle Gold grátis. Encontre tesouros em um tabuleiro 5×5 na selva, crie sua trilha dourada e resgate Liva Credits virtuais. Sem depósitos ou saques.',
    discovery: 'Cada casa segura aumenta sua trilha dourada. Explore a selva, aumente o multiplicador e garanta seu tesouro antes que uma mina encerre a aventura.',
    posterAlt: 'Tabuleiro original de pedra na selva verde-esmeralda, com tesouros dourados e uma trilha de ouro.',
    category: 'Jogos Instantâneos', categoryTitle: 'Encontre tesouros. Crie sua trilha.',
    categoryDescription: 'Nossa aventura original de minas na selva, com créditos virtuais. Separada dos jogos de provedores abaixo.',
    loading: 'Preparando seu tabuleiro na selva…', board: 'Tabuleiro de tesouros da selva', mines: 'Minas', count: 'Quantidade de minas', stake: 'Aposta',
    ready: 'Sua aventura na selva', active: 'Escolha uma casa', cashed_out: 'Tesouro garantido', mine_hit: 'Você encontrou uma mina', result: 'Rodada concluída', error: 'Rodada interrompida',
    start: 'Começar', again: 'Jogar de novo', cash: 'Resgatar', pickFirst: 'Escolha uma casa primeiro', potential: 'Retorno potencial', returned: 'Retorno', profit: 'Resultado líquido',
    safe: 'Segura', mine: 'Mina', hidden: 'Fechada', tile: 'Casa', trail: 'Trilha do tesouro', choose: 'Encontre casas seguras. Garanta seu tesouro.',
    last: 'Último resultado', credits: 'Liva Credits', insufficient: 'Liva Credits insuficientes. Diminua a aposta ou redefina seu saldo demo.',
    unavailable: 'Não foi possível continuar esta rodada com segurança. Volte ao início para tentar de novo.', retry: 'Voltar ao início',
    how: 'Como jogar e pagamentos',
    rules: 'Escolha a aposta e 1, 3, 5, 7 ou 10 minas. Começar gasta sua aposta virtual uma única vez. Todas as minas são posicionadas antes de você escolher uma casa. Casas seguras revelam tesouros e ampliam sua trilha. Uma mina encerra a rodada sem retorno. Resgate após qualquer casa segura; encontrar todas as casas seguras garante o tesouro automaticamente.',
    payouts: 'Com m minas e k casas seguras, a probabilidade de sobreviver é C(25−m,k) / C(25,k). O multiplicador é 0,97 dividido por essa probabilidade: uma única margem demo de 3%, não 3% por casa. Multiplicadores são truncados em seis casas decimais; retornos, na menor unidade de crédito. O multiplicador grande mostra duas casas decimais truncadas; o valor de resgate usa todas as seis. O retorno inclui a aposta. Sem alegação de certificação ou justiça comprovável.',
    interruption: 'Demo local. Recarregar ou sair durante uma rodada mantém a aposta debitada como gasta. Uma rodada inacabada não é retomada nem recebe reembolso ou pagamento automático. Na próxima visita, você começa pronto para jogar.',
    notice: 'Liva Credits não têm valor monetário. Sem depósitos ou saques. Faça pausas e jogue com responsabilidade.',
    realBoundary: 'Explore jogos instantâneos com dinheiro real em operadores aprovados e elegíveis para o mercado selecionado. Liva Mines é nosso Original grátis, não um jogo oferecido por esses operadores.',
  },
  'es-MX': {
    description: 'Juega Liva Mines: Jungle Gold gratis. Descubre tesoros en un tablero selvático de 5×5, crea tu sendero dorado y cobra Liva Credits virtuales. Sin depósitos ni retiros.',
    discovery: 'Cada casilla segura amplía tu sendero dorado. Explora la selva, aumenta el multiplicador y asegura tu tesoro antes de que una mina termine la aventura.',
    posterAlt: 'Tablero original de piedra en una selva esmeralda con tesoros de oro y un sendero dorado.',
    category: 'Juegos Instantáneos', categoryTitle: 'Encuentra tesoros. Crea tu sendero.',
    categoryDescription: 'Nuestra aventura original de minas en la selva con créditos virtuales. Separada de los juegos de proveedores de abajo.',
    loading: 'Preparando tu tablero en la selva…', board: 'Tablero de tesoros de la selva', mines: 'Minas', count: 'Cantidad de minas', stake: 'Apuesta',
    ready: 'Tu aventura en la selva', active: 'Elige una casilla', cashed_out: 'Tesoro asegurado', mine_hit: 'Encontraste una mina', result: 'Ronda terminada', error: 'Ronda interrumpida',
    start: 'Comenzar', again: 'Jugar de nuevo', cash: 'Cobrar', pickFirst: 'Elige una casilla primero', potential: 'Retorno potencial', returned: 'Retorno', profit: 'Resultado neto',
    safe: 'Segura', mine: 'Mina', hidden: 'Sin abrir', tile: 'Casilla', trail: 'Sendero del tesoro', choose: 'Elige casillas seguras. Asegura tu tesoro.',
    last: 'Último resultado', credits: 'Liva Credits', insufficient: 'No tienes suficientes Liva Credits. Reduce la apuesta o restablece tu saldo demo.',
    unavailable: 'No se pudo continuar esta ronda de forma segura. Vuelve al inicio para intentarlo de nuevo.', retry: 'Volver al inicio',
    how: 'Cómo jugar y pagos',
    rules: 'Elige la apuesta y 1, 3, 5, 7 o 10 minas. Comenzar descuenta la apuesta virtual una sola vez. Todas las minas se colocan antes de elegir una casilla. Las casillas seguras revelan tesoros y amplían tu sendero. Una mina termina la ronda sin retorno. Cobra después de cualquier casilla segura; encontrar todas las casillas seguras asegura el tesoro automáticamente.',
    payouts: 'Con m minas y k casillas seguras, la probabilidad de sobrevivir es C(25−m,k) / C(25,k). El multiplicador es 0.97 dividido entre esa probabilidad: un único margen demo del 3%, no un 3% por casilla. Los multiplicadores se truncan a seis decimales; los retornos, a la unidad mínima de crédito. La etiqueta grande muestra dos decimales truncados; el cobro usa los seis. El retorno incluye la apuesta. Sin afirmaciones de certificación ni de equidad demostrable.',
    interruption: 'Demo local. Recargar o salir durante una ronda mantiene la apuesta descontada como gastada. Una ronda sin terminar no se reanuda ni recibe reembolso o pago automático. Tu siguiente visita comienza lista para jugar.',
    notice: 'Liva Credits no tienen valor monetario. Sin depósitos ni retiros. Toma descansos y juega con responsabilidad.',
    realBoundary: 'Explora juegos instantáneos con dinero real en operadores aprobados y elegibles para el mercado seleccionado. Liva Mines es nuestro Original gratuito, no un juego ofrecido por estos operadores.',
  },
}
export const minesCopy = (locale: Locale): MinesCopy => copy[locale]
